// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: tx.proto

package tx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionHeader defines the header for a transaction.
type TransactionHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chainVersion determines the network and code version.
	// First byte: network (devnet, testnet, mainnet, etc.)
	// Bytes 2-4: code version
	// Reserved: 0x0 and 0xFFFFFFFF
	ChainVersion uint32 `protobuf:"fixed32,1,opt,name=chain_version,json=chainVersion,proto3" json:"chain_version,omitempty"`
	// payloadSize defines the length of the payload block.
	// Default: 0x0 (no payload)
	// Reserved: 0xFFFF
	// Max size: 65,532 bytes
	// Total tx size: fixed header size + payload
	PayloadSize uint32 `protobuf:"varint,2,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	// reservedFlag is reserved for future extensions.
	// Default: 0x00
	// Reserved: 0xFF
	ReservedFlag uint32 `protobuf:"varint,3,opt,name=reserved_flag,json=reservedFlag,proto3" json:"reserved_flag,omitempty"`
	// opCode is the command code.
	OpCode uint32 `protobuf:"varint,4,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`
	// authType determines the transaction authorization method.
	// 0x0: UID (default, most common)
	// 0x1: public key (ed25519)
	// 0x2: multisig (public keys and signatories in payload)
	// 0x3: other possible methods
	// Reserved: 0xFF
	AuthType uint32 `protobuf:"varint,5,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	// executionMode determines the execution mode and lifetime.
	// 0x00: default, execute in normal mode
	// 0x01: execute immediately, but before validBefore Height
	// 0x02: execute only in current block
	// 0x03: priority immediate execution, even if other txs
	// 0x04: execute strictly in next block
	// 0x05–0xFF: reserved
	ExecutionMode uint32 `protobuf:"varint,6,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"`
	// reservedPadding is reserved for structure alignment.
	// Default: 0x00
	ReservedPadding uint32 `protobuf:"varint,7,opt,name=reserved_padding,json=reservedPadding,proto3" json:"reserved_padding,omitempty"`
	// marketCode defines the market and trading pair.
	// Default: 0x0 (global chain operation)
	// First 4 bits: market (spot, perp, futures, options, tradfi, etc.)
	// Remaining 28 bits: trading pair ID
	// Reserved: 0xFFFFFFFF
	MarketCode uint32 `protobuf:"fixed32,8,opt,name=market_code,json=marketCode,proto3" json:"market_code,omitempty"`
	// signerUID is the internal user UID of the signer.
	// 0x0 if authType > 0
	SignerUid uint64 `protobuf:"varint,9,opt,name=signer_uid,json=signerUid,proto3" json:"signer_uid,omitempty"`
	// nonce is the account nonce (0 allowed for some service commands).
	Nonce uint64 `protobuf:"varint,10,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// minHeight or lastKnownHeight: last known block height by sender.
	// Tx discarded if current height is lower.
	// Default: 0x0
	MinHeight uint64 `protobuf:"varint,11,opt,name=min_height,json=minHeight,proto3" json:"min_height,omitempty"`
	// maxHeight or validBeforeHeight: height until tx is valid.
	// Default: 0x0
	MaxHeight uint64 `protobuf:"varint,12,opt,name=max_height,json=maxHeight,proto3" json:"max_height,omitempty"`
	// signature is the ed25519 signature.
	Signature     []byte `protobuf:"bytes,13,opt,name=signature,proto3" json:"signature,omitempty"` // Fixed 64 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionHeader) Reset() {
	*x = TransactionHeader{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHeader) ProtoMessage() {}

func (x *TransactionHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHeader.ProtoReflect.Descriptor instead.
func (*TransactionHeader) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionHeader) GetChainVersion() uint32 {
	if x != nil {
		return x.ChainVersion
	}
	return 0
}

func (x *TransactionHeader) GetPayloadSize() uint32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *TransactionHeader) GetReservedFlag() uint32 {
	if x != nil {
		return x.ReservedFlag
	}
	return 0
}

func (x *TransactionHeader) GetOpCode() uint32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *TransactionHeader) GetAuthType() uint32 {
	if x != nil {
		return x.AuthType
	}
	return 0
}

func (x *TransactionHeader) GetExecutionMode() uint32 {
	if x != nil {
		return x.ExecutionMode
	}
	return 0
}

func (x *TransactionHeader) GetReservedPadding() uint32 {
	if x != nil {
		return x.ReservedPadding
	}
	return 0
}

func (x *TransactionHeader) GetMarketCode() uint32 {
	if x != nil {
		return x.MarketCode
	}
	return 0
}

func (x *TransactionHeader) GetSignerUid() uint64 {
	if x != nil {
		return x.SignerUid
	}
	return 0
}

func (x *TransactionHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TransactionHeader) GetMinHeight() uint64 {
	if x != nil {
		return x.MinHeight
	}
	return 0
}

func (x *TransactionHeader) GetMaxHeight() uint64 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

func (x *TransactionHeader) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Transaction - основное сообщение для полной tx.
// Состоит из header и payload (oneof для разных типов в зависимости от opCode).
type Transaction struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *TransactionHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Payload - oneof для типизированных сообщений.
	// Каждый тип payload соответствует конкретному opCode (валидация в коде).
	// Если payload_size == 0, то oneof пустой (nil в Go).
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Transaction_MetaNoop
	//	*Transaction_MetaReserve
	//	*Transaction_OrderCreate
	//	*Transaction_OrderCancel
	//	*Transaction_OrderCancelBatch
	//	*Transaction_OrderCancelAll
	//	*Transaction_OrderCancelReplace
	//	*Transaction_OrderAmend
	//	*Transaction_OrderAmendBatch
	Payload       isTransaction_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetHeader() *TransactionHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Transaction) GetPayload() isTransaction_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Transaction) GetMetaNoop() *MetaNoopPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_MetaNoop); ok {
			return x.MetaNoop
		}
	}
	return nil
}

func (x *Transaction) GetMetaReserve() *MetaReservePayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_MetaReserve); ok {
			return x.MetaReserve
		}
	}
	return nil
}

func (x *Transaction) GetOrderCreate() *OrderCreatePayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderCreate); ok {
			return x.OrderCreate
		}
	}
	return nil
}

func (x *Transaction) GetOrderCancel() *OrderCancelPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderCancel); ok {
			return x.OrderCancel
		}
	}
	return nil
}

func (x *Transaction) GetOrderCancelBatch() *OrderCancelBatchPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderCancelBatch); ok {
			return x.OrderCancelBatch
		}
	}
	return nil
}

func (x *Transaction) GetOrderCancelAll() *OrderCancelAllPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderCancelAll); ok {
			return x.OrderCancelAll
		}
	}
	return nil
}

func (x *Transaction) GetOrderCancelReplace() *OrderCancelReplacePayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderCancelReplace); ok {
			return x.OrderCancelReplace
		}
	}
	return nil
}

func (x *Transaction) GetOrderAmend() *OrderAmendPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderAmend); ok {
			return x.OrderAmend
		}
	}
	return nil
}

func (x *Transaction) GetOrderAmendBatch() *OrderAmendBatchPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderAmendBatch); ok {
			return x.OrderAmendBatch
		}
	}
	return nil
}

type isTransaction_Payload interface {
	isTransaction_Payload()
}

type Transaction_MetaNoop struct {
	// META_NOOP (opCode 0x00): Просто 1 пустой байт (например, bytes с нулевым значением).
	MetaNoop *MetaNoopPayload `protobuf:"bytes,2,opt,name=meta_noop,json=metaNoop,proto3,oneof"`
}

type Transaction_MetaReserve struct {
	// META_RESERVE (opCode 0xFF): Зарезервированная, 1 байт.
	MetaReserve *MetaReservePayload `protobuf:"bytes,3,opt,name=meta_reserve,json=metaReserve,proto3,oneof"`
}

type Transaction_OrderCreate struct {
	// ORD_CREATE (opCode 0x60): Создание ордера.
	OrderCreate *OrderCreatePayload `protobuf:"bytes,4,opt,name=order_create,json=orderCreate,proto3,oneof"`
}

type Transaction_OrderCancel struct {
	// ORD_CANCEL (opCode 0x64): Отмена одного ордера.
	OrderCancel *OrderCancelPayload `protobuf:"bytes,5,opt,name=order_cancel,json=orderCancel,proto3,oneof"`
}

type Transaction_OrderCancelBatch struct {
	// ORD_CANCEL_BATCH (opCode 0x65): Массовая отмена.
	OrderCancelBatch *OrderCancelBatchPayload `protobuf:"bytes,6,opt,name=order_cancel_batch,json=orderCancelBatch,proto3,oneof"`
}

type Transaction_OrderCancelAll struct {
	// ORD_CANCEL_ALL (opCode 0x66): Отмена всех ордеров (payload пустой, но для oneof используем пустое сообщение).
	OrderCancelAll *OrderCancelAllPayload `protobuf:"bytes,7,opt,name=order_cancel_all,json=orderCancelAll,proto3,oneof"`
}

type Transaction_OrderCancelReplace struct {
	// ORD_CANCEL_REPLACE (opCode 0x6A): Атомарная отмена и создание.
	OrderCancelReplace *OrderCancelReplacePayload `protobuf:"bytes,8,opt,name=order_cancel_replace,json=orderCancelReplace,proto3,oneof"`
}

type Transaction_OrderAmend struct {
	// ORD_AMEND (opCode 0x6B): Изменение ордера.
	OrderAmend *OrderAmendPayload `protobuf:"bytes,9,opt,name=order_amend,json=orderAmend,proto3,oneof"`
}

type Transaction_OrderAmendBatch struct {
	// ORD_AMEND_BATCH (opCode 0x6C): Массовое изменение.
	OrderAmendBatch *OrderAmendBatchPayload `protobuf:"bytes,10,opt,name=order_amend_batch,json=orderAmendBatch,proto3,oneof"`
}

func (*Transaction_MetaNoop) isTransaction_Payload() {}

func (*Transaction_MetaReserve) isTransaction_Payload() {}

func (*Transaction_OrderCreate) isTransaction_Payload() {}

func (*Transaction_OrderCancel) isTransaction_Payload() {}

func (*Transaction_OrderCancelBatch) isTransaction_Payload() {}

func (*Transaction_OrderCancelAll) isTransaction_Payload() {}

func (*Transaction_OrderCancelReplace) isTransaction_Payload() {}

func (*Transaction_OrderAmend) isTransaction_Payload() {}

func (*Transaction_OrderAmendBatch) isTransaction_Payload() {}

// MetaNoopPayload - для META_NOOP (opCode 0x00).
type MetaNoopPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // 1 байт, default пустой (0x00)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaNoopPayload) Reset() {
	*x = MetaNoopPayload{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaNoopPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaNoopPayload) ProtoMessage() {}

func (x *MetaNoopPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaNoopPayload.ProtoReflect.Descriptor instead.
func (*MetaNoopPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MetaNoopPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// MetaReservePayload - для META_RESERVE (opCode 0xFF).
type MetaReservePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // 1 байт, default пустой
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaReservePayload) Reset() {
	*x = MetaReservePayload{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaReservePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaReservePayload) ProtoMessage() {}

func (x *MetaReservePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaReservePayload.ProtoReflect.Descriptor instead.
func (*MetaReservePayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MetaReservePayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// OrderID - 16 байт, UUIDv7
type OrderID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Фиксированные 16 байт.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderID) Reset() {
	*x = OrderID{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderID) ProtoMessage() {}

func (x *OrderID) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderID.ProtoReflect.Descriptor instead.
func (*OrderID) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *OrderID) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// OrderCreatePayload - для ORD_CREATE (opCode 0x60).
type OrderCreatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *OrderID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`     // OrderID - 16 байт, UUIDv7
	IsBuy         bool                   `protobuf:"varint,2,opt,name=is_buy,json=isBuy,proto3" json:"is_buy,omitempty"`          // Buy/Sell side.
	IsMarket      bool                   `protobuf:"varint,3,opt,name=is_market,json=isMarket,proto3" json:"is_market,omitempty"` // true: рыночный ордер, false: лимитный.
	Quantity      uint64                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                 // Объем в base units.
	Price         uint64                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`                       // Цена в quote units (игнорируется для market).
	Flags         uint32                 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`                       // Флаги: битовые (e.g., bit0: GTD, bit1: IOC, etc.). Определите маску в коде.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatePayload) Reset() {
	*x = OrderCreatePayload{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatePayload) ProtoMessage() {}

func (x *OrderCreatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatePayload.ProtoReflect.Descriptor instead.
func (*OrderCreatePayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *OrderCreatePayload) GetOrderId() *OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OrderCreatePayload) GetIsBuy() bool {
	if x != nil {
		return x.IsBuy
	}
	return false
}

func (x *OrderCreatePayload) GetIsMarket() bool {
	if x != nil {
		return x.IsMarket
	}
	return false
}

func (x *OrderCreatePayload) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderCreatePayload) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderCreatePayload) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// OrderCancelPayload - для ORD_CANCEL (opCode 0x64).
type OrderCancelPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *OrderID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // OrderID - 16 байт, UUIDv7
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelPayload) Reset() {
	*x = OrderCancelPayload{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelPayload) ProtoMessage() {}

func (x *OrderCancelPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelPayload.ProtoReflect.Descriptor instead.
func (*OrderCancelPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *OrderCancelPayload) GetOrderId() *OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

// OrderCancelBatchPayload - для ORD_CANCEL_BATCH (opCode 0x65).
type OrderCancelBatchPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderIds      []*OrderID             `protobuf:"bytes,1,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"` // Массив orderID (каждый 16 байт)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelBatchPayload) Reset() {
	*x = OrderCancelBatchPayload{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelBatchPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelBatchPayload) ProtoMessage() {}

func (x *OrderCancelBatchPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelBatchPayload.ProtoReflect.Descriptor instead.
func (*OrderCancelBatchPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *OrderCancelBatchPayload) GetOrderIds() []*OrderID {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

// OrderCancelAllPayload - для ORD_CANCEL_ALL (opCode 0x66).
type OrderCancelAllPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // 1 байт, default пустой
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelAllPayload) Reset() {
	*x = OrderCancelAllPayload{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelAllPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelAllPayload) ProtoMessage() {}

func (x *OrderCancelAllPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelAllPayload.ProtoReflect.Descriptor instead.
func (*OrderCancelAllPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *OrderCancelAllPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// OrderCancelReplacePayload - для ORD_CANCEL_REPLACE (opCode 0x6A).
type OrderCancelReplacePayload struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderId *OrderID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // OrderID - 16 байт, UUIDv7
	// Затем создание нового (аналогично OrderCreatePayload).
	IsBuy         bool     `protobuf:"varint,2,opt,name=is_buy,json=isBuy,proto3" json:"is_buy,omitempty"`                 // Buy/Sell side.
	IsMarket      bool     `protobuf:"varint,3,opt,name=is_market,json=isMarket,proto3" json:"is_market,omitempty"`        // true: рыночный ордер, false: лимитный.
	Quantity      uint64   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                        // Объем в base units.
	Price         uint64   `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`                              // Цена в quote units (игнорируется для market).
	Flags         uint32   `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`                              // Флаги: битовые (e.g., bit0: GTD, bit1: IOC, etc.). Определите маску в коде.
	NewOrderId    *OrderID `protobuf:"bytes,7,opt,name=new_order_id,json=newOrderId,proto3" json:"new_order_id,omitempty"` // Новый ордер
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelReplacePayload) Reset() {
	*x = OrderCancelReplacePayload{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelReplacePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelReplacePayload) ProtoMessage() {}

func (x *OrderCancelReplacePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelReplacePayload.ProtoReflect.Descriptor instead.
func (*OrderCancelReplacePayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

func (x *OrderCancelReplacePayload) GetOrderId() *OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OrderCancelReplacePayload) GetIsBuy() bool {
	if x != nil {
		return x.IsBuy
	}
	return false
}

func (x *OrderCancelReplacePayload) GetIsMarket() bool {
	if x != nil {
		return x.IsMarket
	}
	return false
}

func (x *OrderCancelReplacePayload) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderCancelReplacePayload) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderCancelReplacePayload) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *OrderCancelReplacePayload) GetNewOrderId() *OrderID {
	if x != nil {
		return x.NewOrderId
	}
	return nil
}

// OrderAmendPayload - для ORD_AMEND (opCode 0x6B).
type OrderAmendPayload struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderId *OrderID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // OrderID - 16 байт, UUIDv7
	// Изменяемые поля (опционально, если не указано - не менять).
	Quantity      *uint64 `protobuf:"varint,2,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Price         *uint64 `protobuf:"varint,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAmendPayload) Reset() {
	*x = OrderAmendPayload{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAmendPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAmendPayload) ProtoMessage() {}

func (x *OrderAmendPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAmendPayload.ProtoReflect.Descriptor instead.
func (*OrderAmendPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *OrderAmendPayload) GetOrderId() *OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OrderAmendPayload) GetQuantity() uint64 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *OrderAmendPayload) GetPrice() uint64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

// OrderAmendBatchPayload - для ORD_AMEND_BATCH (opCode 0x6C).
// Для каждого ордера: ID + изменения.
type OrderAmendBatchPayload struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Amends        []*OrderAmendBatchPayload_AmendItem `protobuf:"bytes,1,rep,name=amends,proto3" json:"amends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAmendBatchPayload) Reset() {
	*x = OrderAmendBatchPayload{}
	mi := &file_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAmendBatchPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAmendBatchPayload) ProtoMessage() {}

func (x *OrderAmendBatchPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAmendBatchPayload.ProtoReflect.Descriptor instead.
func (*OrderAmendBatchPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11}
}

func (x *OrderAmendBatchPayload) GetAmends() []*OrderAmendBatchPayload_AmendItem {
	if x != nil {
		return x.Amends
	}
	return nil
}

type OrderAmendBatchPayload_AmendItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *OrderID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // OrderID - 16 байт, UUIDv7
	Quantity      *uint64                `protobuf:"varint,2,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Price         *uint64                `protobuf:"varint,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAmendBatchPayload_AmendItem) Reset() {
	*x = OrderAmendBatchPayload_AmendItem{}
	mi := &file_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAmendBatchPayload_AmendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAmendBatchPayload_AmendItem) ProtoMessage() {}

func (x *OrderAmendBatchPayload_AmendItem) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAmendBatchPayload_AmendItem.ProtoReflect.Descriptor instead.
func (*OrderAmendBatchPayload_AmendItem) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11, 0}
}

func (x *OrderAmendBatchPayload_AmendItem) GetOrderId() *OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OrderAmendBatchPayload_AmendItem) GetQuantity() uint64 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *OrderAmendBatchPayload_AmendItem) GetPrice() uint64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x02tx\"\xba\x03\n" +
	"\x11TransactionHeader\x12#\n" +
	"\rchain_version\x18\x01 \x01(\aR\fchainVersion\x12!\n" +
	"\fpayload_size\x18\x02 \x01(\rR\vpayloadSize\x12#\n" +
	"\rreserved_flag\x18\x03 \x01(\rR\freservedFlag\x12\x17\n" +
	"\aop_code\x18\x04 \x01(\rR\x06opCode\x12\x1b\n" +
	"\tauth_type\x18\x05 \x01(\rR\bauthType\x12%\n" +
	"\x0eexecution_mode\x18\x06 \x01(\rR\rexecutionMode\x12)\n" +
	"\x10reserved_padding\x18\a \x01(\rR\x0freservedPadding\x12\x1f\n" +
	"\vmarket_code\x18\b \x01(\aR\n" +
	"marketCode\x12\x1d\n" +
	"\n" +
	"signer_uid\x18\t \x01(\x04R\tsignerUid\x12\x14\n" +
	"\x05nonce\x18\n" +
	" \x01(\x04R\x05nonce\x12\x1d\n" +
	"\n" +
	"min_height\x18\v \x01(\x04R\tminHeight\x12\x1d\n" +
	"\n" +
	"max_height\x18\f \x01(\x04R\tmaxHeight\x12\x1c\n" +
	"\tsignature\x18\r \x01(\fR\tsignature\"\x9d\x05\n" +
	"\vTransaction\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.tx.TransactionHeaderR\x06header\x122\n" +
	"\tmeta_noop\x18\x02 \x01(\v2\x13.tx.MetaNoopPayloadH\x00R\bmetaNoop\x12;\n" +
	"\fmeta_reserve\x18\x03 \x01(\v2\x16.tx.MetaReservePayloadH\x00R\vmetaReserve\x12;\n" +
	"\forder_create\x18\x04 \x01(\v2\x16.tx.OrderCreatePayloadH\x00R\vorderCreate\x12;\n" +
	"\forder_cancel\x18\x05 \x01(\v2\x16.tx.OrderCancelPayloadH\x00R\vorderCancel\x12K\n" +
	"\x12order_cancel_batch\x18\x06 \x01(\v2\x1b.tx.OrderCancelBatchPayloadH\x00R\x10orderCancelBatch\x12E\n" +
	"\x10order_cancel_all\x18\a \x01(\v2\x19.tx.OrderCancelAllPayloadH\x00R\x0eorderCancelAll\x12Q\n" +
	"\x14order_cancel_replace\x18\b \x01(\v2\x1d.tx.OrderCancelReplacePayloadH\x00R\x12orderCancelReplace\x128\n" +
	"\vorder_amend\x18\t \x01(\v2\x15.tx.OrderAmendPayloadH\x00R\n" +
	"orderAmend\x12H\n" +
	"\x11order_amend_batch\x18\n" +
	" \x01(\v2\x1a.tx.OrderAmendBatchPayloadH\x00R\x0forderAmendBatchB\t\n" +
	"\apayload\"+\n" +
	"\x0fMetaNoopPayload\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\".\n" +
	"\x12MetaReservePayload\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x19\n" +
	"\aOrderID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xb8\x01\n" +
	"\x12OrderCreatePayload\x12&\n" +
	"\border_id\x18\x01 \x01(\v2\v.tx.OrderIDR\aorderId\x12\x15\n" +
	"\x06is_buy\x18\x02 \x01(\bR\x05isBuy\x12\x1b\n" +
	"\tis_market\x18\x03 \x01(\bR\bisMarket\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x04R\x05price\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\rR\x05flags\"<\n" +
	"\x12OrderCancelPayload\x12&\n" +
	"\border_id\x18\x01 \x01(\v2\v.tx.OrderIDR\aorderId\"C\n" +
	"\x17OrderCancelBatchPayload\x12(\n" +
	"\torder_ids\x18\x01 \x03(\v2\v.tx.OrderIDR\borderIds\"1\n" +
	"\x15OrderCancelAllPayload\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\xee\x01\n" +
	"\x19OrderCancelReplacePayload\x12&\n" +
	"\border_id\x18\x01 \x01(\v2\v.tx.OrderIDR\aorderId\x12\x15\n" +
	"\x06is_buy\x18\x02 \x01(\bR\x05isBuy\x12\x1b\n" +
	"\tis_market\x18\x03 \x01(\bR\bisMarket\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x04R\x05price\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\rR\x05flags\x12-\n" +
	"\fnew_order_id\x18\a \x01(\v2\v.tx.OrderIDR\n" +
	"newOrderId\"\x8e\x01\n" +
	"\x11OrderAmendPayload\x12&\n" +
	"\border_id\x18\x01 \x01(\v2\v.tx.OrderIDR\aorderId\x12\x1f\n" +
	"\bquantity\x18\x02 \x01(\x04H\x00R\bquantity\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x04H\x01R\x05price\x88\x01\x01B\v\n" +
	"\t_quantityB\b\n" +
	"\x06_price\"\xdf\x01\n" +
	"\x16OrderAmendBatchPayload\x12<\n" +
	"\x06amends\x18\x01 \x03(\v2$.tx.OrderAmendBatchPayload.AmendItemR\x06amends\x1a\x86\x01\n" +
	"\tAmendItem\x12&\n" +
	"\border_id\x18\x01 \x01(\v2\v.tx.OrderIDR\aorderId\x12\x1f\n" +
	"\bquantity\x18\x02 \x01(\x04H\x00R\bquantity\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x04H\x01R\x05price\x88\x01\x01B\v\n" +
	"\t_quantityB\b\n" +
	"\x06_priceB\x05Z\x03/txb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tx_proto_goTypes = []any{
	(*TransactionHeader)(nil),                // 0: tx.TransactionHeader
	(*Transaction)(nil),                      // 1: tx.Transaction
	(*MetaNoopPayload)(nil),                  // 2: tx.MetaNoopPayload
	(*MetaReservePayload)(nil),               // 3: tx.MetaReservePayload
	(*OrderID)(nil),                          // 4: tx.OrderID
	(*OrderCreatePayload)(nil),               // 5: tx.OrderCreatePayload
	(*OrderCancelPayload)(nil),               // 6: tx.OrderCancelPayload
	(*OrderCancelBatchPayload)(nil),          // 7: tx.OrderCancelBatchPayload
	(*OrderCancelAllPayload)(nil),            // 8: tx.OrderCancelAllPayload
	(*OrderCancelReplacePayload)(nil),        // 9: tx.OrderCancelReplacePayload
	(*OrderAmendPayload)(nil),                // 10: tx.OrderAmendPayload
	(*OrderAmendBatchPayload)(nil),           // 11: tx.OrderAmendBatchPayload
	(*OrderAmendBatchPayload_AmendItem)(nil), // 12: tx.OrderAmendBatchPayload.AmendItem
}
var file_tx_proto_depIdxs = []int32{
	0,  // 0: tx.Transaction.header:type_name -> tx.TransactionHeader
	2,  // 1: tx.Transaction.meta_noop:type_name -> tx.MetaNoopPayload
	3,  // 2: tx.Transaction.meta_reserve:type_name -> tx.MetaReservePayload
	5,  // 3: tx.Transaction.order_create:type_name -> tx.OrderCreatePayload
	6,  // 4: tx.Transaction.order_cancel:type_name -> tx.OrderCancelPayload
	7,  // 5: tx.Transaction.order_cancel_batch:type_name -> tx.OrderCancelBatchPayload
	8,  // 6: tx.Transaction.order_cancel_all:type_name -> tx.OrderCancelAllPayload
	9,  // 7: tx.Transaction.order_cancel_replace:type_name -> tx.OrderCancelReplacePayload
	10, // 8: tx.Transaction.order_amend:type_name -> tx.OrderAmendPayload
	11, // 9: tx.Transaction.order_amend_batch:type_name -> tx.OrderAmendBatchPayload
	4,  // 10: tx.OrderCreatePayload.order_id:type_name -> tx.OrderID
	4,  // 11: tx.OrderCancelPayload.order_id:type_name -> tx.OrderID
	4,  // 12: tx.OrderCancelBatchPayload.order_ids:type_name -> tx.OrderID
	4,  // 13: tx.OrderCancelReplacePayload.order_id:type_name -> tx.OrderID
	4,  // 14: tx.OrderCancelReplacePayload.new_order_id:type_name -> tx.OrderID
	4,  // 15: tx.OrderAmendPayload.order_id:type_name -> tx.OrderID
	12, // 16: tx.OrderAmendBatchPayload.amends:type_name -> tx.OrderAmendBatchPayload.AmendItem
	4,  // 17: tx.OrderAmendBatchPayload.AmendItem.order_id:type_name -> tx.OrderID
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	file_tx_proto_msgTypes[1].OneofWrappers = []any{
		(*Transaction_MetaNoop)(nil),
		(*Transaction_MetaReserve)(nil),
		(*Transaction_OrderCreate)(nil),
		(*Transaction_OrderCancel)(nil),
		(*Transaction_OrderCancelBatch)(nil),
		(*Transaction_OrderCancelAll)(nil),
		(*Transaction_OrderCancelReplace)(nil),
		(*Transaction_OrderAmend)(nil),
		(*Transaction_OrderAmendBatch)(nil),
	}
	file_tx_proto_msgTypes[10].OneofWrappers = []any{}
	file_tx_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
