// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: order.proto

package benchmark

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Оптимизированная структура с группировкой полей по размеру
// для лучшего выравнивания памяти
type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 64-bit fields grouped together
	Uid           uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nonce         uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Price         uint64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Amount        uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	LinkedOrderId uint64 `protobuf:"varint,5,opt,name=linked_order_id,json=linkedOrderId,proto3" json:"linked_order_id,omitempty"`
	// Fixed-size byte arrays
	Signature   []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                          // 32 bytes
	UserOrderId string `protobuf:"bytes,7,opt,name=user_order_id,json=userOrderId,proto3" json:"user_order_id,omitempty"` // 16 bytes string
	// Symbol as 4-byte fixed string
	Symbol []byte `protobuf:"bytes,8,opt,name=symbol,proto3" json:"symbol,omitempty"` // 4 bytes
	// Single byte fields at the end
	OpCode        uint32 `protobuf:"varint,9,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`              // 1 byte as uint32
	Flags         uint32 `protobuf:"varint,10,opt,name=flags,proto3" json:"flags,omitempty"`                             // 1 byte as uint32
	OrdersFlag    uint32 `protobuf:"varint,11,opt,name=orders_flag,json=ordersFlag,proto3" json:"orders_flag,omitempty"` // 1 byte as uint32
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Order) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Order) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetLinkedOrderId() uint64 {
	if x != nil {
		return x.LinkedOrderId
	}
	return 0
}

func (x *Order) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Order) GetUserOrderId() string {
	if x != nil {
		return x.UserOrderId
	}
	return ""
}

func (x *Order) GetSymbol() []byte {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *Order) GetOpCode() uint32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *Order) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Order) GetOrdersFlag() uint32 {
	if x != nil {
		return x.OrdersFlag
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\tbenchmark\"\xaf\x02\n" +
	"\x05Order\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12&\n" +
	"\x0flinked_order_id\x18\x05 \x01(\x04R\rlinkedOrderId\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12\"\n" +
	"\ruser_order_id\x18\a \x01(\tR\vuserOrderId\x12\x16\n" +
	"\x06symbol\x18\b \x01(\fR\x06symbol\x12\x17\n" +
	"\aop_code\x18\t \x01(\rR\x06opCode\x12\x14\n" +
	"\x05flags\x18\n" +
	" \x01(\rR\x05flags\x12\x1f\n" +
	"\vorders_flag\x18\v \x01(\rR\n" +
	"ordersFlagB\"Z github.com/yourproject/benchmarkb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_proto_goTypes = []any{
	(*Order)(nil), // 0: benchmark.Order
}
var file_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
