// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: tx.proto

package tx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип сети
type ChainType int32

const (
	ChainType_DEVNET         ChainType = 0
	ChainType_TESTNET        ChainType = 1
	ChainType_PUBLIC_TESTNET ChainType = 2
	ChainType_MAINNET_V1     ChainType = 3
	ChainType_MAINNET_V2     ChainType = 4
	ChainType_MAINNET_V3     ChainType = 5
	ChainType_DARKNET        ChainType = 6
	ChainType_CI_AUTOTEST    ChainType = 7
	ChainType_LOCALNET       ChainType = 8
)

// Enum value maps for ChainType.
var (
	ChainType_name = map[int32]string{
		0: "DEVNET",
		1: "TESTNET",
		2: "PUBLIC_TESTNET",
		3: "MAINNET_V1",
		4: "MAINNET_V2",
		5: "MAINNET_V3",
		6: "DARKNET",
		7: "CI_AUTOTEST",
		8: "LOCALNET",
	}
	ChainType_value = map[string]int32{
		"DEVNET":         0,
		"TESTNET":        1,
		"PUBLIC_TESTNET": 2,
		"MAINNET_V1":     3,
		"MAINNET_V2":     4,
		"MAINNET_V3":     5,
		"DARKNET":        6,
		"CI_AUTOTEST":    7,
		"LOCALNET":       8,
	}
)

func (x ChainType) Enum() *ChainType {
	p := new(ChainType)
	*p = x
	return p
}

func (x ChainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainType) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[0].Descriptor()
}

func (ChainType) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[0]
}

func (x ChainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainType.Descriptor instead.
func (ChainType) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

// Спецификация вариантов аутенфикации транзакции
type TxAuthType int32

const (
	TxAuthType_UID           TxAuthType = 0 //внутренний UID
	TxAuthType_BATCHED       TxAuthType = 1 //Указывает, что это батч, где отдельные транзакции не имеют своих подписей
	TxAuthType_ED25519_PK    TxAuthType = 2 //Public key ed25519
	TxAuthType_ED25519_MSIG  TxAuthType = 3 //Multisig
	TxAuthType_SEC256k1_PK   TxAuthType = 4 //На будущее оставим
	TxAuthType_SEC256k1_MSIG TxAuthType = 5 //На будущее оставим
	TxAuthType_UNKNOWN       TxAuthType = 6
)

// Enum value maps for TxAuthType.
var (
	TxAuthType_name = map[int32]string{
		0: "UID",
		1: "BATCHED",
		2: "ED25519_PK",
		3: "ED25519_MSIG",
		4: "SEC256k1_PK",
		5: "SEC256k1_MSIG",
		6: "UNKNOWN",
	}
	TxAuthType_value = map[string]int32{
		"UID":           0,
		"BATCHED":       1,
		"ED25519_PK":    2,
		"ED25519_MSIG":  3,
		"SEC256k1_PK":   4,
		"SEC256k1_MSIG": 5,
		"UNKNOWN":       6,
	}
)

func (x TxAuthType) Enum() *TxAuthType {
	p := new(TxAuthType)
	*p = x
	return p
}

func (x TxAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[1].Descriptor()
}

func (TxAuthType) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[1]
}

func (x TxAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxAuthType.Descriptor instead.
func (TxAuthType) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

// Определяет режим исполнения транзакции и время ее жизни
type TxExecMode int32

const (
	TxExecMode_DEFAULT       TxExecMode = 0
	TxExecMode_ASAP          TxExecMode = 1 //исполнить сразу, но до указанного validBeforeHeight
	TxExecMode_IMMEDIATLY    TxExecMode = 2 //приоритет исполнение немедленно, даже если есть другие tx
	TxExecMode_CURRENT_BLOCK TxExecMode = 3 //исполнение только в текущем блоке
	TxExecMode_NEXT_BLOCK    TxExecMode = 4 //исполнение строго в следующем блок
)

// Enum value maps for TxExecMode.
var (
	TxExecMode_name = map[int32]string{
		0: "DEFAULT",
		1: "ASAP",
		2: "IMMEDIATLY",
		3: "CURRENT_BLOCK",
		4: "NEXT_BLOCK",
	}
	TxExecMode_value = map[string]int32{
		"DEFAULT":       0,
		"ASAP":          1,
		"IMMEDIATLY":    2,
		"CURRENT_BLOCK": 3,
		"NEXT_BLOCK":    4,
	}
)

func (x TxExecMode) Enum() *TxExecMode {
	p := new(TxExecMode)
	*p = x
	return p
}

func (x TxExecMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxExecMode) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[2].Descriptor()
}

func (TxExecMode) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[2]
}

func (x TxExecMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxExecMode.Descriptor instead.
func (TxExecMode) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

// Опишем рынки
type Markets int32

const (
	Markets_UNDEFINED         Markets = 0 //Дефолт - операция глобал, не в рынке
	Markets_PERPETUAL         Markets = 1 //Стандартные перпы
	Markets_SPOT              Markets = 2 //Классический спот
	Markets_AMM_SWAP          Markets = 3 //зарезервируем для свопов через AMM
	Markets_INVERSE_PERP      Markets = 4 //Inverse linear contracts
	Markets_VANILLA_OPTIONS   Markets = 5
	Markets_PERPETUAL_OPTIONS Markets = 6
	Markets_DIGITAL_OPTIONS   Markets = 7
	Markets_PREDICTION        Markets = 8  // Для рынков предсказаний
	Markets_TRADFI            Markets = 9  // Для рынков токенезированных акций
	Markets_INDICES           Markets = 10 // Рынки индексов
	Markets_EXOTIC            Markets = 11 //Спишем все остальное
)

// Enum value maps for Markets.
var (
	Markets_name = map[int32]string{
		0:  "UNDEFINED",
		1:  "PERPETUAL",
		2:  "SPOT",
		3:  "AMM_SWAP",
		4:  "INVERSE_PERP",
		5:  "VANILLA_OPTIONS",
		6:  "PERPETUAL_OPTIONS",
		7:  "DIGITAL_OPTIONS",
		8:  "PREDICTION",
		9:  "TRADFI",
		10: "INDICES",
		11: "EXOTIC",
	}
	Markets_value = map[string]int32{
		"UNDEFINED":         0,
		"PERPETUAL":         1,
		"SPOT":              2,
		"AMM_SWAP":          3,
		"INVERSE_PERP":      4,
		"VANILLA_OPTIONS":   5,
		"PERPETUAL_OPTIONS": 6,
		"DIGITAL_OPTIONS":   7,
		"PREDICTION":        8,
		"TRADFI":            9,
		"INDICES":           10,
		"EXOTIC":            11,
	}
)

func (x Markets) Enum() *Markets {
	p := new(Markets)
	*p = x
	return p
}

func (x Markets) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Markets) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[3].Descriptor()
}

func (Markets) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[3]
}

func (x Markets) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Markets.Descriptor instead.
func (Markets) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

// Опишем все наши команды
type OpCode int32

const (
	OpCode_META_NOOP                           OpCode = 0
	OpCode_META_BLOB                           OpCode = 1
	OpCode_META_RESERVE                        OpCode = 2
	OpCode_META_BATCH                          OpCode = 3
	OpCode_SYS_UPGRADE                         OpCode = 4
	OpCode_SYS_PAUSE                           OpCode = 5
	OpCode_SYS_RESUME                          OpCode = 6
	OpCode_SYS_SET_FLAG                        OpCode = 7
	OpCode_SYS_HEARTBEAT_CHECK                 OpCode = 8
	OpCode_SYS_UPDATE_VALIDATOR_PARAMS         OpCode = 9
	OpCode_SYS_DEPOSIT_PAUSE                   OpCode = 10
	OpCode_SYS_WITHDRAW_PAUSE                  OpCode = 11
	OpCode_SYS_DEPOSIT_RESUME                  OpCode = 12
	OpCode_SYS_WITHDRAW_RESUME                 OpCode = 13
	OpCode_INS_FUND_CREATE                     OpCode = 14
	OpCode_INS_FUND_OP                         OpCode = 15
	OpCode_INS_CREDIT                          OpCode = 16
	OpCode_INS_REPAY                           OpCode = 17
	OpCode_INS_PAYOUT                          OpCode = 18
	OpCode_INS_AUTO_REBALANCE                  OpCode = 19
	OpCode_GOV_ASSET_CREATE                    OpCode = 20
	OpCode_GOV_ASSET_UPDATE                    OpCode = 21
	OpCode_GOV_MARKET_CREATE                   OpCode = 22
	OpCode_GOV_MARKET_UPDATE                   OpCode = 23
	OpCode_GOV_MARKET_FREEZE                   OpCode = 24
	OpCode_GOV_MARKET_UNFREEZE                 OpCode = 25
	OpCode_GOV_MARKET_SETTLE                   OpCode = 26
	OpCode_GOV_MARKET_DELIST                   OpCode = 27
	OpCode_GOV_SET_ACC_FEE_TIER                OpCode = 28
	OpCode_GOV_FEE_COLLECT                     OpCode = 29
	OpCode_GOV_INDX_ORACLE_FEED                OpCode = 30
	OpCode_GOV_INDX_VALUE                      OpCode = 31
	OpCode_GOV_MARKET_FUNDING                  OpCode = 32
	OpCode_GOV_BALANCE_TRANSFER                OpCode = 33
	OpCode_GOV_FEE_SCHEDULE_UPDATE             OpCode = 34
	OpCode_GOV_MESSAGE                         OpCode = 35
	OpCode_GOV_APPROVE_PROPOSE                 OpCode = 36
	OpCode_GOV_VAULT_CREATE                    OpCode = 37
	OpCode_GOV_VAULT_PAUSE_DEPOSITS            OpCode = 38
	OpCode_GOV_VAULT_RESUME_DEPOSITS           OpCode = 39
	OpCode_GOV_VAULT_EMERGENCY_ENABLE_WITHDRAW OpCode = 40
	OpCode_ACC_REGISTER                        OpCode = 41
	OpCode_ACC_DEPOSIT                         OpCode = 42
	OpCode_ACC_WITHDRAW_REQUEST                OpCode = 43
	OpCode_ACC_WITHDRAW_CLAIM                  OpCode = 44
	OpCode_ACC_WALLET_TRANSFER                 OpCode = 45
	OpCode_ACC_SET_FLAG                        OpCode = 46
	OpCode_ACC_FEE_PAY                         OpCode = 47
	OpCode_ACC_AGENT_REGISTER                  OpCode = 48
	OpCode_ACC_AGENT_REVOKE                    OpCode = 49
	OpCode_ACC_AGENT_UPDATE_LIMITS             OpCode = 50
	OpCode_ACC_SUBACCOUNT_CREATE               OpCode = 51
	OpCode_ACC_SESSION_HEARTBEAT               OpCode = 52
	OpCode_ACC_NONCE_UPDATE                    OpCode = 53
	OpCode_ACC_WHITELIST_ADD                   OpCode = 54
	OpCode_ACC_WHITELIST_REMOVE                OpCode = 55
	OpCode_ACC_KYC_SUBMIT_PROOF                OpCode = 56
	OpCode_ACC_MESSAGE                         OpCode = 57
	OpCode_ACC_UPDATE_MESSAGE_KEY              OpCode = 58
	OpCode_ACC_VOTE                            OpCode = 59
	OpCode_ACC_CREATE_PROPOSE                  OpCode = 60
	OpCode_ORD_CREATE                          OpCode = 61
	OpCode_ORD_CANCEL                          OpCode = 62
	OpCode_ORD_CANCEL_ALL                      OpCode = 63
	OpCode_ORD_CANCEL_REPLACE                  OpCode = 64
	OpCode_ORD_AMEND                           OpCode = 65
	OpCode_ORD_REORDER                         OpCode = 69
	OpCode_POS_MARGIN_ADJ                      OpCode = 70
	OpCode_POS_CLOSE                           OpCode = 71
	OpCode_POS_LEVERAGE                        OpCode = 72
	OpCode_POS_ADL                             OpCode = 73
	OpCode_POS_SETTLE                          OpCode = 74
	OpCode_ERC20_TRANSFER                      OpCode = 75
	OpCode_ERC20_MINT                          OpCode = 76
	OpCode_ERC20_BURN                          OpCode = 77
	OpCode_ERC20_APPROVE                       OpCode = 78
	OpCode_ERC20_FREEZE                        OpCode = 79
	OpCode_ERC20_UNFREEZE                      OpCode = 80
	OpCode_VAULT_DEPOSIT                       OpCode = 81
	OpCode_VAULT_WITHDRAW_REQUEST              OpCode = 82
	OpCode_VAULT_WITHDRAW_CLAIM                OpCode = 83
	OpCode_VAULT_REWARDS_CLAIM                 OpCode = 84
	OpCode_VAULT_TOPUP_REWARDS                 OpCode = 85
	OpCode_VAULT_EMERGENCY_WITHDRAW            OpCode = 86
	OpCode_KYC_COMPLIANCE_FLAG_SET             OpCode = 87
	OpCode_KYC_COMPLIANCE_KYC_UPDATE           OpCode = 88
	OpCode_KYC_COMPLIANCE_FREEZE               OpCode = 89
	OpCode_KYC_COMPLIANCE_UNFREEZE             OpCode = 90
	OpCode_KYC_SANCTIONS_LIST_UPDATE           OpCode = 91
	OpCode_UNKNOWN_OR_UNREALISED               OpCode = 2047
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0:    "META_NOOP",
		1:    "META_BLOB",
		2:    "META_RESERVE",
		3:    "META_BATCH",
		4:    "SYS_UPGRADE",
		5:    "SYS_PAUSE",
		6:    "SYS_RESUME",
		7:    "SYS_SET_FLAG",
		8:    "SYS_HEARTBEAT_CHECK",
		9:    "SYS_UPDATE_VALIDATOR_PARAMS",
		10:   "SYS_DEPOSIT_PAUSE",
		11:   "SYS_WITHDRAW_PAUSE",
		12:   "SYS_DEPOSIT_RESUME",
		13:   "SYS_WITHDRAW_RESUME",
		14:   "INS_FUND_CREATE",
		15:   "INS_FUND_OP",
		16:   "INS_CREDIT",
		17:   "INS_REPAY",
		18:   "INS_PAYOUT",
		19:   "INS_AUTO_REBALANCE",
		20:   "GOV_ASSET_CREATE",
		21:   "GOV_ASSET_UPDATE",
		22:   "GOV_MARKET_CREATE",
		23:   "GOV_MARKET_UPDATE",
		24:   "GOV_MARKET_FREEZE",
		25:   "GOV_MARKET_UNFREEZE",
		26:   "GOV_MARKET_SETTLE",
		27:   "GOV_MARKET_DELIST",
		28:   "GOV_SET_ACC_FEE_TIER",
		29:   "GOV_FEE_COLLECT",
		30:   "GOV_INDX_ORACLE_FEED",
		31:   "GOV_INDX_VALUE",
		32:   "GOV_MARKET_FUNDING",
		33:   "GOV_BALANCE_TRANSFER",
		34:   "GOV_FEE_SCHEDULE_UPDATE",
		35:   "GOV_MESSAGE",
		36:   "GOV_APPROVE_PROPOSE",
		37:   "GOV_VAULT_CREATE",
		38:   "GOV_VAULT_PAUSE_DEPOSITS",
		39:   "GOV_VAULT_RESUME_DEPOSITS",
		40:   "GOV_VAULT_EMERGENCY_ENABLE_WITHDRAW",
		41:   "ACC_REGISTER",
		42:   "ACC_DEPOSIT",
		43:   "ACC_WITHDRAW_REQUEST",
		44:   "ACC_WITHDRAW_CLAIM",
		45:   "ACC_WALLET_TRANSFER",
		46:   "ACC_SET_FLAG",
		47:   "ACC_FEE_PAY",
		48:   "ACC_AGENT_REGISTER",
		49:   "ACC_AGENT_REVOKE",
		50:   "ACC_AGENT_UPDATE_LIMITS",
		51:   "ACC_SUBACCOUNT_CREATE",
		52:   "ACC_SESSION_HEARTBEAT",
		53:   "ACC_NONCE_UPDATE",
		54:   "ACC_WHITELIST_ADD",
		55:   "ACC_WHITELIST_REMOVE",
		56:   "ACC_KYC_SUBMIT_PROOF",
		57:   "ACC_MESSAGE",
		58:   "ACC_UPDATE_MESSAGE_KEY",
		59:   "ACC_VOTE",
		60:   "ACC_CREATE_PROPOSE",
		61:   "ORD_CREATE",
		62:   "ORD_CANCEL",
		63:   "ORD_CANCEL_ALL",
		64:   "ORD_CANCEL_REPLACE",
		65:   "ORD_AMEND",
		69:   "ORD_REORDER",
		70:   "POS_MARGIN_ADJ",
		71:   "POS_CLOSE",
		72:   "POS_LEVERAGE",
		73:   "POS_ADL",
		74:   "POS_SETTLE",
		75:   "ERC20_TRANSFER",
		76:   "ERC20_MINT",
		77:   "ERC20_BURN",
		78:   "ERC20_APPROVE",
		79:   "ERC20_FREEZE",
		80:   "ERC20_UNFREEZE",
		81:   "VAULT_DEPOSIT",
		82:   "VAULT_WITHDRAW_REQUEST",
		83:   "VAULT_WITHDRAW_CLAIM",
		84:   "VAULT_REWARDS_CLAIM",
		85:   "VAULT_TOPUP_REWARDS",
		86:   "VAULT_EMERGENCY_WITHDRAW",
		87:   "KYC_COMPLIANCE_FLAG_SET",
		88:   "KYC_COMPLIANCE_KYC_UPDATE",
		89:   "KYC_COMPLIANCE_FREEZE",
		90:   "KYC_COMPLIANCE_UNFREEZE",
		91:   "KYC_SANCTIONS_LIST_UPDATE",
		2047: "UNKNOWN_OR_UNREALISED",
	}
	OpCode_value = map[string]int32{
		"META_NOOP":                           0,
		"META_BLOB":                           1,
		"META_RESERVE":                        2,
		"META_BATCH":                          3,
		"SYS_UPGRADE":                         4,
		"SYS_PAUSE":                           5,
		"SYS_RESUME":                          6,
		"SYS_SET_FLAG":                        7,
		"SYS_HEARTBEAT_CHECK":                 8,
		"SYS_UPDATE_VALIDATOR_PARAMS":         9,
		"SYS_DEPOSIT_PAUSE":                   10,
		"SYS_WITHDRAW_PAUSE":                  11,
		"SYS_DEPOSIT_RESUME":                  12,
		"SYS_WITHDRAW_RESUME":                 13,
		"INS_FUND_CREATE":                     14,
		"INS_FUND_OP":                         15,
		"INS_CREDIT":                          16,
		"INS_REPAY":                           17,
		"INS_PAYOUT":                          18,
		"INS_AUTO_REBALANCE":                  19,
		"GOV_ASSET_CREATE":                    20,
		"GOV_ASSET_UPDATE":                    21,
		"GOV_MARKET_CREATE":                   22,
		"GOV_MARKET_UPDATE":                   23,
		"GOV_MARKET_FREEZE":                   24,
		"GOV_MARKET_UNFREEZE":                 25,
		"GOV_MARKET_SETTLE":                   26,
		"GOV_MARKET_DELIST":                   27,
		"GOV_SET_ACC_FEE_TIER":                28,
		"GOV_FEE_COLLECT":                     29,
		"GOV_INDX_ORACLE_FEED":                30,
		"GOV_INDX_VALUE":                      31,
		"GOV_MARKET_FUNDING":                  32,
		"GOV_BALANCE_TRANSFER":                33,
		"GOV_FEE_SCHEDULE_UPDATE":             34,
		"GOV_MESSAGE":                         35,
		"GOV_APPROVE_PROPOSE":                 36,
		"GOV_VAULT_CREATE":                    37,
		"GOV_VAULT_PAUSE_DEPOSITS":            38,
		"GOV_VAULT_RESUME_DEPOSITS":           39,
		"GOV_VAULT_EMERGENCY_ENABLE_WITHDRAW": 40,
		"ACC_REGISTER":                        41,
		"ACC_DEPOSIT":                         42,
		"ACC_WITHDRAW_REQUEST":                43,
		"ACC_WITHDRAW_CLAIM":                  44,
		"ACC_WALLET_TRANSFER":                 45,
		"ACC_SET_FLAG":                        46,
		"ACC_FEE_PAY":                         47,
		"ACC_AGENT_REGISTER":                  48,
		"ACC_AGENT_REVOKE":                    49,
		"ACC_AGENT_UPDATE_LIMITS":             50,
		"ACC_SUBACCOUNT_CREATE":               51,
		"ACC_SESSION_HEARTBEAT":               52,
		"ACC_NONCE_UPDATE":                    53,
		"ACC_WHITELIST_ADD":                   54,
		"ACC_WHITELIST_REMOVE":                55,
		"ACC_KYC_SUBMIT_PROOF":                56,
		"ACC_MESSAGE":                         57,
		"ACC_UPDATE_MESSAGE_KEY":              58,
		"ACC_VOTE":                            59,
		"ACC_CREATE_PROPOSE":                  60,
		"ORD_CREATE":                          61,
		"ORD_CANCEL":                          62,
		"ORD_CANCEL_ALL":                      63,
		"ORD_CANCEL_REPLACE":                  64,
		"ORD_AMEND":                           65,
		"ORD_REORDER":                         69,
		"POS_MARGIN_ADJ":                      70,
		"POS_CLOSE":                           71,
		"POS_LEVERAGE":                        72,
		"POS_ADL":                             73,
		"POS_SETTLE":                          74,
		"ERC20_TRANSFER":                      75,
		"ERC20_MINT":                          76,
		"ERC20_BURN":                          77,
		"ERC20_APPROVE":                       78,
		"ERC20_FREEZE":                        79,
		"ERC20_UNFREEZE":                      80,
		"VAULT_DEPOSIT":                       81,
		"VAULT_WITHDRAW_REQUEST":              82,
		"VAULT_WITHDRAW_CLAIM":                83,
		"VAULT_REWARDS_CLAIM":                 84,
		"VAULT_TOPUP_REWARDS":                 85,
		"VAULT_EMERGENCY_WITHDRAW":            86,
		"KYC_COMPLIANCE_FLAG_SET":             87,
		"KYC_COMPLIANCE_KYC_UPDATE":           88,
		"KYC_COMPLIANCE_FREEZE":               89,
		"KYC_COMPLIANCE_UNFREEZE":             90,
		"KYC_SANCTIONS_LIST_UPDATE":           91,
		"UNKNOWN_OR_UNREALISED":               2047,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[4].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[4]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

// Группируем флаги в enum-ы
type Side int32

const (
	Side_BUY  Side = 0
	Side_SELL Side = 1
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	Side_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[5].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[5]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

// Тип ордера
type OrderType int32

const (
	OrderType_MARKET      OrderType = 0
	OrderType_LIMIT       OrderType = 1
	OrderType_STOP_MARKET OrderType = 2
	OrderType_STOP_LIMIT  OrderType = 3
	OrderType_TAKE_MARKET OrderType = 4
	OrderType_TAKE_LIMIT  OrderType = 5
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "MARKET",
		1: "LIMIT",
		2: "STOP_MARKET",
		3: "STOP_LIMIT",
		4: "TAKE_MARKET",
		5: "TAKE_LIMIT",
	}
	OrderType_value = map[string]int32{
		"MARKET":      0,
		"LIMIT":       1,
		"STOP_MARKET": 2,
		"STOP_LIMIT":  3,
		"TAKE_MARKET": 4,
		"TAKE_LIMIT":  5,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[6].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[6]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

// Спецификация исполнения
type TimeInForce int32

const (
	TimeInForce_GTC TimeInForce = 0
	TimeInForce_IOC TimeInForce = 1
	TimeInForce_FOK TimeInForce = 2
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "GTC",
		1: "IOC",
		2: "FOK",
	}
	TimeInForce_value = map[string]int32{
		"GTC": 0,
		"IOC": 1,
		"FOK": 2,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[7].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[7]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

// Спецификация Trigger-price
type TriggerPrice int32

const (
	TriggerPrice_MARKPRICE      TriggerPrice = 0
	TriggerPrice_SPOTPRICE      TriggerPrice = 1
	TriggerPrice_LASTTRADEPRICE TriggerPrice = 2
	TriggerPrice_FUNDINGRATE    TriggerPrice = 3
)

// Enum value maps for TriggerPrice.
var (
	TriggerPrice_name = map[int32]string{
		0: "MARKPRICE",
		1: "SPOTPRICE",
		2: "LASTTRADEPRICE",
		3: "FUNDINGRATE",
	}
	TriggerPrice_value = map[string]int32{
		"MARKPRICE":      0,
		"SPOTPRICE":      1,
		"LASTTRADEPRICE": 2,
		"FUNDINGRATE":    3,
	}
)

func (x TriggerPrice) Enum() *TriggerPrice {
	p := new(TriggerPrice)
	*p = x
	return p
}

func (x TriggerPrice) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerPrice) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[8].Descriptor()
}

func (TriggerPrice) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[8]
}

func (x TriggerPrice) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerPrice.Descriptor instead.
func (TriggerPrice) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

// Для простой поддержки Multi-sig мы добавим отдельный вид пейлоада
// Важно - храним для аккаунта или же в системной таблице сколько подписей надо для каждой команды
// Мы фиксируем что максимм 5 подписей будет (n-of-5)
type SigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignerUid     uint64                 `protobuf:"varint,1,opt,name=signer_uid,json=signerUid,proto3" json:"signer_uid,omitempty"` // UID который подписывает
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`                          // Sequence number аккаунта
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                   // Ed25519 индивидуальная подпись
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigEntry) Reset() {
	*x = SigEntry{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigEntry) ProtoMessage() {}

func (x *SigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigEntry.ProtoReflect.Descriptor instead.
func (*SigEntry) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *SigEntry) GetSignerUid() uint64 {
	if x != nil {
		return x.SignerUid
	}
	return 0
}

func (x *SigEntry) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *SigEntry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Специальный пейлоад структура, минимум 2 подписи всегда будет
type MultiSigBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Sig1  *SigEntry              `protobuf:"bytes,1,opt,name=sig1,proto3" json:"sig1,omitempty"`
	Sig2  *SigEntry              `protobuf:"bytes,2,opt,name=sig2,proto3" json:"sig2,omitempty"`
	// остальные опционально
	Sig3          *SigEntry `protobuf:"bytes,3,opt,name=sig3,proto3,oneof" json:"sig3,omitempty"`
	Sig4          *SigEntry `protobuf:"bytes,4,opt,name=sig4,proto3,oneof" json:"sig4,omitempty"`
	Sig5          *SigEntry `protobuf:"bytes,5,opt,name=sig5,proto3,oneof" json:"sig5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiSigBlock) Reset() {
	*x = MultiSigBlock{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiSigBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSigBlock) ProtoMessage() {}

func (x *MultiSigBlock) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSigBlock.ProtoReflect.Descriptor instead.
func (*MultiSigBlock) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MultiSigBlock) GetSig1() *SigEntry {
	if x != nil {
		return x.Sig1
	}
	return nil
}

func (x *MultiSigBlock) GetSig2() *SigEntry {
	if x != nil {
		return x.Sig2
	}
	return nil
}

func (x *MultiSigBlock) GetSig3() *SigEntry {
	if x != nil {
		return x.Sig3
	}
	return nil
}

func (x *MultiSigBlock) GetSig4() *SigEntry {
	if x != nil {
		return x.Sig4
	}
	return nil
}

func (x *MultiSigBlock) GetSig5() *SigEntry {
	if x != nil {
		return x.Sig5
	}
	return nil
}

// Новое сообщение-контейнер, чтобы рассылать блок, состоящий из массива суб-блоков, экономим на парсинге
type TransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []*Transaction         `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionList) GetTxs() []*Transaction {
	if x != nil {
		return x.Txs
	}
	return nil
}

// TransactionHeader defines the header for a transaction.
type TransactionHeader struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChainType ChainType              `protobuf:"varint,1,opt,name=chain_type,json=chainType,proto3,enum=tx.ChainType" json:"chain_type,omitempty"`
	// chainVersion determines the code version.
	ChainVersion uint32 `protobuf:"varint,2,opt,name=chain_version,json=chainVersion,proto3" json:"chain_version,omitempty"`
	// opCode is the command code.
	OpCode OpCode `protobuf:"varint,3,opt,name=op_code,json=opCode,proto3,enum=tx.OpCode" json:"op_code,omitempty"`
	// authType determines the transaction authorization method.
	AuthType TxAuthType `protobuf:"varint,4,opt,name=auth_type,json=authType,proto3,enum=tx.TxAuthType" json:"auth_type,omitempty"`
	// executionMode determines the execution mode and lifetime.
	ExecutionMode TxExecMode `protobuf:"varint,5,opt,name=execution_mode,json=executionMode,proto3,enum=tx.TxExecMode" json:"execution_mode,omitempty"`
	// marketCode defines the market
	// Default: 0x0 (global chain operation)
	MarketCode Markets `protobuf:"varint,6,opt,name=market_code,json=marketCode,proto3,enum=tx.Markets" json:"market_code,omitempty"`
	// И теперь отдельно код торговой пары
	MarketSymbol uint32 `protobuf:"varint,7,opt,name=market_symbol,json=marketSymbol,proto3" json:"market_symbol,omitempty"`
	// signerUID is the internal user UID of the signer.
	SignerUid uint64 `protobuf:"varint,8,opt,name=signer_uid,json=signerUid,proto3" json:"signer_uid,omitempty"`
	// nonce is the account nonce (0 allowed for some service commands).
	Nonce uint64 `protobuf:"varint,9,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// minHeight or lastKnownHeight: last known block height by sender.
	// Tx discarded if current height is lower.
	// Default: 0x0
	MinHeight uint64 `protobuf:"varint,10,opt,name=min_height,json=minHeight,proto3" json:"min_height,omitempty"`
	// maxHeight or validBeforeHeight: height until tx is valid.
	// Default: 0x0
	MaxHeight uint64 `protobuf:"varint,11,opt,name=max_height,json=maxHeight,proto3" json:"max_height,omitempty"`
	// signature is the ed25519 signature.
	// Опционально (для батча), но так как это bytes нет нужды указывать optional
	Signature     []byte `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"` //[(vtproto.ext).allow_alias = true] // Fixed 64 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionHeader) Reset() {
	*x = TransactionHeader{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHeader) ProtoMessage() {}

func (x *TransactionHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHeader.ProtoReflect.Descriptor instead.
func (*TransactionHeader) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionHeader) GetChainType() ChainType {
	if x != nil {
		return x.ChainType
	}
	return ChainType_DEVNET
}

func (x *TransactionHeader) GetChainVersion() uint32 {
	if x != nil {
		return x.ChainVersion
	}
	return 0
}

func (x *TransactionHeader) GetOpCode() OpCode {
	if x != nil {
		return x.OpCode
	}
	return OpCode_META_NOOP
}

func (x *TransactionHeader) GetAuthType() TxAuthType {
	if x != nil {
		return x.AuthType
	}
	return TxAuthType_UID
}

func (x *TransactionHeader) GetExecutionMode() TxExecMode {
	if x != nil {
		return x.ExecutionMode
	}
	return TxExecMode_DEFAULT
}

func (x *TransactionHeader) GetMarketCode() Markets {
	if x != nil {
		return x.MarketCode
	}
	return Markets_UNDEFINED
}

func (x *TransactionHeader) GetMarketSymbol() uint32 {
	if x != nil {
		return x.MarketSymbol
	}
	return 0
}

func (x *TransactionHeader) GetSignerUid() uint64 {
	if x != nil {
		return x.SignerUid
	}
	return 0
}

func (x *TransactionHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TransactionHeader) GetMinHeight() uint64 {
	if x != nil {
		return x.MinHeight
	}
	return 0
}

func (x *TransactionHeader) GetMaxHeight() uint64 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

func (x *TransactionHeader) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// BatchedTransactionHeader defines the small header for a transaction, grouped at batch ONLY!
type BatchedTransactionHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// opCode is the command code.
	OpCode OpCode `protobuf:"varint,1,opt,name=op_code,json=opCode,proto3,enum=tx.OpCode" json:"op_code,omitempty"`
	// marketCode defines the market
	// Default: 0x0 (global chain operation)
	MarketCode Markets `protobuf:"varint,2,opt,name=market_code,json=marketCode,proto3,enum=tx.Markets" json:"market_code,omitempty"`
	// И теперь отдельно код торговой пары
	MarketSymbol uint32 `protobuf:"varint,3,opt,name=market_symbol,json=marketSymbol,proto3" json:"market_symbol,omitempty"`
	// nonce is the account nonce (0 allowed for some service commands).
	Nonce         uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedTransactionHeader) Reset() {
	*x = BatchedTransactionHeader{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedTransactionHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedTransactionHeader) ProtoMessage() {}

func (x *BatchedTransactionHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedTransactionHeader.ProtoReflect.Descriptor instead.
func (*BatchedTransactionHeader) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *BatchedTransactionHeader) GetOpCode() OpCode {
	if x != nil {
		return x.OpCode
	}
	return OpCode_META_NOOP
}

func (x *BatchedTransactionHeader) GetMarketCode() Markets {
	if x != nil {
		return x.MarketCode
	}
	return Markets_UNDEFINED
}

func (x *BatchedTransactionHeader) GetMarketSymbol() uint32 {
	if x != nil {
		return x.MarketSymbol
	}
	return 0
}

func (x *BatchedTransactionHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// Transaction - основное сообщение для полной tx.
// Состоит из header и payload (oneof для разных типов в зависимости от opCode).
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to HeaderData:
	//
	//	*Transaction_Header
	//	*Transaction_BatchHeader
	HeaderData isTransaction_HeaderData `protobuf_oneof:"header_data"`
	// Payload - oneof для типизированных сообщений.
	// Каждый тип payload соответствует конкретному opCode (валидация в коде).
	// Если payload_size == 0, то oneof пустой (nil в Go).
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Transaction_MetaNoop
	//	*Transaction_MetaBlob
	//	*Transaction_MetaReserve
	//	*Transaction_OrderCreate
	//	*Transaction_OrderCancel
	//	*Transaction_OrderCancelAll
	//	*Transaction_OrderCancelReplace
	//	*Transaction_OrderAmend
	//	*Transaction_SysUpgrade
	Payload       isTransaction_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *Transaction) GetHeaderData() isTransaction_HeaderData {
	if x != nil {
		return x.HeaderData
	}
	return nil
}

func (x *Transaction) GetHeader() *TransactionHeader {
	if x != nil {
		if x, ok := x.HeaderData.(*Transaction_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *Transaction) GetBatchHeader() *BatchedTransactionHeader {
	if x != nil {
		if x, ok := x.HeaderData.(*Transaction_BatchHeader); ok {
			return x.BatchHeader
		}
	}
	return nil
}

func (x *Transaction) GetPayload() isTransaction_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Transaction) GetMetaNoop() *MetaNoopPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_MetaNoop); ok {
			return x.MetaNoop
		}
	}
	return nil
}

func (x *Transaction) GetMetaBlob() *MetaBlobPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_MetaBlob); ok {
			return x.MetaBlob
		}
	}
	return nil
}

func (x *Transaction) GetMetaReserve() *MetaReservePayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_MetaReserve); ok {
			return x.MetaReserve
		}
	}
	return nil
}

func (x *Transaction) GetOrderCreate() *OrderCreatePayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderCreate); ok {
			return x.OrderCreate
		}
	}
	return nil
}

func (x *Transaction) GetOrderCancel() *OrderCancelPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderCancel); ok {
			return x.OrderCancel
		}
	}
	return nil
}

func (x *Transaction) GetOrderCancelAll() *OrderCancelAllPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderCancelAll); ok {
			return x.OrderCancelAll
		}
	}
	return nil
}

func (x *Transaction) GetOrderCancelReplace() *OrderCancelReplacePayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderCancelReplace); ok {
			return x.OrderCancelReplace
		}
	}
	return nil
}

func (x *Transaction) GetOrderAmend() *OrderAmendPayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_OrderAmend); ok {
			return x.OrderAmend
		}
	}
	return nil
}

func (x *Transaction) GetSysUpgrade() *SysUpgradePayload {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_SysUpgrade); ok {
			return x.SysUpgrade
		}
	}
	return nil
}

type isTransaction_HeaderData interface {
	isTransaction_HeaderData()
}

type Transaction_Header struct {
	Header *TransactionHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"` // Полный заголовок (id=1 для совместимости)
}

type Transaction_BatchHeader struct {
	BatchHeader *BatchedTransactionHeader `protobuf:"bytes,2,opt,name=batch_header,json=batchHeader,proto3,oneof"` // Легкий заголовок
}

func (*Transaction_Header) isTransaction_HeaderData() {}

func (*Transaction_BatchHeader) isTransaction_HeaderData() {}

type isTransaction_Payload interface {
	isTransaction_Payload()
}

type Transaction_MetaNoop struct {
	// META_NOOP (opCode 0x00): Просто 1 пустой байт (например, bytes с нулевым значением).
	MetaNoop *MetaNoopPayload `protobuf:"bytes,3,opt,name=meta_noop,json=metaNoop,proto3,oneof"`
}

type Transaction_MetaBlob struct {
	// META_BLOB - служебная транзакция, произвольный блок который добавляет только пропоусер
	MetaBlob *MetaBlobPayload `protobuf:"bytes,4,opt,name=meta_blob,json=metaBlob,proto3,oneof"`
}

type Transaction_MetaReserve struct {
	// META_RESERVE (opCode 0xFF): Зарезервированная, 1 байт.
	MetaReserve *MetaReservePayload `protobuf:"bytes,5,opt,name=meta_reserve,json=metaReserve,proto3,oneof"`
}

type Transaction_OrderCreate struct {
	// ORD_CREATE (opCode 0x60): Создание ордера.
	OrderCreate *OrderCreatePayload `protobuf:"bytes,6,opt,name=order_create,json=orderCreate,proto3,oneof"`
}

type Transaction_OrderCancel struct {
	// ORD_CANCEL (opCode 0x64): Отмена одного ордера.
	OrderCancel *OrderCancelPayload `protobuf:"bytes,7,opt,name=order_cancel,json=orderCancel,proto3,oneof"`
}

type Transaction_OrderCancelAll struct {
	// ORD_CANCEL_ALL (opCode 0x66): Отмена всех ордеров (payload пустой, но для oneof используем пустое сообщение).
	OrderCancelAll *OrderCancelAllPayload `protobuf:"bytes,8,opt,name=order_cancel_all,json=orderCancelAll,proto3,oneof"`
}

type Transaction_OrderCancelReplace struct {
	// ORD_CANCEL_REPLACE (opCode 0x6A): Атомарная отмена и создание (батчинг НЕ поддерживаеться).
	OrderCancelReplace *OrderCancelReplacePayload `protobuf:"bytes,9,opt,name=order_cancel_replace,json=orderCancelReplace,proto3,oneof"`
}

type Transaction_OrderAmend struct {
	// ORD_AMEND (opCode 0x6B): Изменение ордера (с поддержкой батчинга).
	OrderAmend *OrderAmendPayload `protobuf:"bytes,10,opt,name=order_amend,json=orderAmend,proto3,oneof"`
}

type Transaction_SysUpgrade struct {
	SysUpgrade *SysUpgradePayload `protobuf:"bytes,101,opt,name=sys_upgrade,json=sysUpgrade,proto3,oneof"` //ТЕСТ
}

func (*Transaction_MetaNoop) isTransaction_Payload() {}

func (*Transaction_MetaBlob) isTransaction_Payload() {}

func (*Transaction_MetaReserve) isTransaction_Payload() {}

func (*Transaction_OrderCreate) isTransaction_Payload() {}

func (*Transaction_OrderCancel) isTransaction_Payload() {}

func (*Transaction_OrderCancelAll) isTransaction_Payload() {}

func (*Transaction_OrderCancelReplace) isTransaction_Payload() {}

func (*Transaction_OrderAmend) isTransaction_Payload() {}

func (*Transaction_SysUpgrade) isTransaction_Payload() {}

// ТОЛЬКО для специальной команды META_BATCH
// Содержит полный заголовок и подпись, встроеные сообщения же - только краткий
// Это ползволит комбинировать любые тразакции из поддерживаемых системой (кроме вложенных батчей, конечно!)
type BatchTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TransactionHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`   // Полный заголовок
	Payload       []*Transaction         `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty"` //Содержит любое количесто сообщений с обычными транзакциями (но с упрощенными заголовками!)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTransaction) Reset() {
	*x = BatchTransaction{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTransaction) ProtoMessage() {}

func (x *BatchTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTransaction.ProtoReflect.Descriptor instead.
func (*BatchTransaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *BatchTransaction) GetHeader() *TransactionHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BatchTransaction) GetPayload() []*Transaction {
	if x != nil {
		return x.Payload
	}
	return nil
}

// MetaNoopPayload - для META_NOOP (opCode 0x00).
type MetaNoopPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // 1 байт, default пустой (0x00)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaNoopPayload) Reset() {
	*x = MetaNoopPayload{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaNoopPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaNoopPayload) ProtoMessage() {}

func (x *MetaNoopPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaNoopPayload.ProtoReflect.Descriptor instead.
func (*MetaNoopPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MetaNoopPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// MetaReservePayload - для META_RESERVE (opCode 0xFF).
type MetaReservePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // 1 байт, default пустой
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaReservePayload) Reset() {
	*x = MetaReservePayload{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaReservePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaReservePayload) ProtoMessage() {}

func (x *MetaReservePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaReservePayload.ProtoReflect.Descriptor instead.
func (*MetaReservePayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MetaReservePayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SYS_UPGRADE - тестируем первую команду с мультисигом
type SysUpgradePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MultiSig      *MultiSigBlock         `protobuf:"bytes,1,opt,name=multi_sig,json=multiSig,proto3" json:"multi_sig,omitempty"` //Первым идет блок мульти-подписей
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                   //Зарезервируем для реального пейлоада дальше
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUpgradePayload) Reset() {
	*x = SysUpgradePayload{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUpgradePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUpgradePayload) ProtoMessage() {}

func (x *SysUpgradePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUpgradePayload.ProtoReflect.Descriptor instead.
func (*SysUpgradePayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

func (x *SysUpgradePayload) GetMultiSig() *MultiSigBlock {
	if x != nil {
		return x.MultiSig
	}
	return nil
}

func (x *SysUpgradePayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// OrderID - 16 байт, UUIDv7
type OrderID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` //[(vtproto.ext).allow_alias = true]  // Фиксированные 16 байт.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderID) Reset() {
	*x = OrderID{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderID) ProtoMessage() {}

func (x *OrderID) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderID.ProtoReflect.Descriptor instead.
func (*OrderID) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *OrderID) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// База - новый ордер
type OrderItem struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	OrderId   *OrderID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                          // OrderID - 16 байт, UUIDv7
	Side      Side                   `protobuf:"varint,2,opt,name=side,proto3,enum=tx.Side" json:"side,omitempty"`                                 //Buy/Sell side, BUY is default
	OrderType OrderType              `protobuf:"varint,3,opt,name=order_type,json=orderType,proto3,enum=tx.OrderType" json:"order_type,omitempty"` //Тип ордера, маркет дефолтный
	ExecType  TimeInForce            `protobuf:"varint,4,opt,name=exec_type,json=execType,proto3,enum=tx.TimeInForce" json:"exec_type,omitempty"`  //Спецификация исполнения - GTC default
	// Несмотря на то, что многие относят эти поля к спецификации выполнения, лучше выделит отдельно
	ReduceOnly bool   `protobuf:"varint,5,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	PostOnly   bool   `protobuf:"varint,6,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	Quantity   uint64 `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"` // Объем в base units.
	Price      uint64 `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`       // Цена в quote units (игнорируется для market).
	// Попробуем указать параметры стопов и тейков
	StopPriceType *TriggerPrice `protobuf:"varint,9,opt,name=stop_price_type,json=stopPriceType,proto3,enum=tx.TriggerPrice,oneof" json:"stop_price_type,omitempty"`  // Тип цены для стоп-ордера
	StopPrice     *uint64       `protobuf:"varint,10,opt,name=stop_price,json=stopPrice,proto3,oneof" json:"stop_price,omitempty"`                                    // Само значение (то есть - цена из списка TriggerPrice), 0 для маркет или цена для лимитного
	TakePriceType *TriggerPrice `protobuf:"varint,11,opt,name=take_price_type,json=takePriceType,proto3,enum=tx.TriggerPrice,oneof" json:"take_price_type,omitempty"` // Тип цены для тейк-ордера
	TakePrice     *uint64       `protobuf:"varint,12,opt,name=take_price,json=takePrice,proto3,oneof" json:"take_price,omitempty"`                                    // Само значение (то есть - цена из списка TriggerPrice)
	MarketCode    *uint32       `protobuf:"varint,13,opt,name=market_code,json=marketCode,proto3,oneof" json:"market_code,omitempty"`                                 //Опционально, укажем код рынка (compressed, uint32) для мульти-маркет батчинга
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11}
}

func (x *OrderItem) GetOrderId() *OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OrderItem) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_BUY
}

func (x *OrderItem) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_MARKET
}

func (x *OrderItem) GetExecType() TimeInForce {
	if x != nil {
		return x.ExecType
	}
	return TimeInForce_GTC
}

func (x *OrderItem) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *OrderItem) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *OrderItem) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetStopPriceType() TriggerPrice {
	if x != nil && x.StopPriceType != nil {
		return *x.StopPriceType
	}
	return TriggerPrice_MARKPRICE
}

func (x *OrderItem) GetStopPrice() uint64 {
	if x != nil && x.StopPrice != nil {
		return *x.StopPrice
	}
	return 0
}

func (x *OrderItem) GetTakePriceType() TriggerPrice {
	if x != nil && x.TakePriceType != nil {
		return *x.TakePriceType
	}
	return TriggerPrice_MARKPRICE
}

func (x *OrderItem) GetTakePrice() uint64 {
	if x != nil && x.TakePrice != nil {
		return *x.TakePrice
	}
	return 0
}

func (x *OrderItem) GetMarketCode() uint32 {
	if x != nil && x.MarketCode != nil {
		return *x.MarketCode
	}
	return 0
}

// Базовый блок для модификации ордера - пока можно менять только цену или обьем
type AmendItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *OrderID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // OrderID - 16 байт, UUIDv7
	Quantity      *uint64                `protobuf:"varint,2,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Price         *uint64                `protobuf:"varint,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	StopPriceType *TriggerPrice          `protobuf:"varint,4,opt,name=stop_price_type,json=stopPriceType,proto3,enum=tx.TriggerPrice,oneof" json:"stop_price_type,omitempty"` // Тип цены для стоп-ордера
	StopPrice     *uint64                `protobuf:"varint,5,opt,name=stop_price,json=stopPrice,proto3,oneof" json:"stop_price,omitempty"`                                    // Само значение (то есть - цена из списка TriggerPrice), 0 для маркет или цена для лимитного
	TakePriceType *TriggerPrice          `protobuf:"varint,6,opt,name=take_price_type,json=takePriceType,proto3,enum=tx.TriggerPrice,oneof" json:"take_price_type,omitempty"` // Тип цены для тейк-ордера
	TakePrice     *uint64                `protobuf:"varint,7,opt,name=take_price,json=takePrice,proto3,oneof" json:"take_price,omitempty"`                                    // Само значение (то есть - цена из списка TriggerPrice)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmendItem) Reset() {
	*x = AmendItem{}
	mi := &file_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmendItem) ProtoMessage() {}

func (x *AmendItem) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmendItem.ProtoReflect.Descriptor instead.
func (*AmendItem) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{12}
}

func (x *AmendItem) GetOrderId() *OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *AmendItem) GetQuantity() uint64 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *AmendItem) GetPrice() uint64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *AmendItem) GetStopPriceType() TriggerPrice {
	if x != nil && x.StopPriceType != nil {
		return *x.StopPriceType
	}
	return TriggerPrice_MARKPRICE
}

func (x *AmendItem) GetStopPrice() uint64 {
	if x != nil && x.StopPrice != nil {
		return *x.StopPrice
	}
	return 0
}

func (x *AmendItem) GetTakePriceType() TriggerPrice {
	if x != nil && x.TakePriceType != nil {
		return *x.TakePriceType
	}
	return TriggerPrice_MARKPRICE
}

func (x *AmendItem) GetTakePrice() uint64 {
	if x != nil && x.TakePrice != nil {
		return *x.TakePrice
	}
	return 0
}

// TODO: MetaBlobPayload
type MetaBlobPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // [(vtproto.ext).allow_alias = true];
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaBlobPayload) Reset() {
	*x = MetaBlobPayload{}
	mi := &file_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaBlobPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaBlobPayload) ProtoMessage() {}

func (x *MetaBlobPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaBlobPayload.ProtoReflect.Descriptor instead.
func (*MetaBlobPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{13}
}

func (x *MetaBlobPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// TODO: MetaBatchPayload
type MetaBatchPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // 1 байт, default пустой
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaBatchPayload) Reset() {
	*x = MetaBatchPayload{}
	mi := &file_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaBatchPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaBatchPayload) ProtoMessage() {}

func (x *MetaBatchPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaBatchPayload.ProtoReflect.Descriptor instead.
func (*MetaBatchPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{14}
}

func (x *MetaBatchPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// OrderCreatePayload - для ORD_CREATE (opCode 0x60).
type OrderCreatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderItem           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"` //Сразу любое количество новых ордеров
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatePayload) Reset() {
	*x = OrderCreatePayload{}
	mi := &file_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatePayload) ProtoMessage() {}

func (x *OrderCreatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatePayload.ProtoReflect.Descriptor instead.
func (*OrderCreatePayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{15}
}

func (x *OrderCreatePayload) GetOrders() []*OrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

// OrderCancelPayload - для ORD_CANCEL (opCode 0x64), поддерживает батчинг сразу
type OrderCancelPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       []*OrderID             `protobuf:"bytes,1,rep,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // OrderID - 16 байт, UUIDv7
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelPayload) Reset() {
	*x = OrderCancelPayload{}
	mi := &file_tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelPayload) ProtoMessage() {}

func (x *OrderCancelPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelPayload.ProtoReflect.Descriptor instead.
func (*OrderCancelPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{16}
}

func (x *OrderCancelPayload) GetOrderId() []*OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

// OrderCancelAllPayload - для ORD_CANCEL_ALL (opCode 0x66).
type OrderCancelAllPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // 1 байт, default пустой
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelAllPayload) Reset() {
	*x = OrderCancelAllPayload{}
	mi := &file_tx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelAllPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelAllPayload) ProtoMessage() {}

func (x *OrderCancelAllPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelAllPayload.ProtoReflect.Descriptor instead.
func (*OrderCancelAllPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{17}
}

func (x *OrderCancelAllPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// OrderCancelReplacePayload - для ORD_CANCEL_REPLACE (opCode 0x6A). Батчинг таких ордеров не поддерживаеться
type OrderCancelReplacePayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CanceledOrderId *OrderID               `protobuf:"bytes,1,opt,name=canceled_order_id,json=canceledOrderId,proto3" json:"canceled_order_id,omitempty"` // OrderID того ордера, который заменяем.
	// Новый ордер
	ReplacedOrder *OrderCreatePayload `protobuf:"bytes,2,opt,name=replaced_order,json=replacedOrder,proto3" json:"replaced_order,omitempty"` // Новый ордер (и OrderID внутри новый)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelReplacePayload) Reset() {
	*x = OrderCancelReplacePayload{}
	mi := &file_tx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelReplacePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelReplacePayload) ProtoMessage() {}

func (x *OrderCancelReplacePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelReplacePayload.ProtoReflect.Descriptor instead.
func (*OrderCancelReplacePayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{18}
}

func (x *OrderCancelReplacePayload) GetCanceledOrderId() *OrderID {
	if x != nil {
		return x.CanceledOrderId
	}
	return nil
}

func (x *OrderCancelReplacePayload) GetReplacedOrder() *OrderCreatePayload {
	if x != nil {
		return x.ReplacedOrder
	}
	return nil
}

// OrderAmendPayload - для ORD_AMEND (opCode 0x6B), автоматическая поддержка BATCH-инга
// Для каждого ордера: ID + изменения.
type OrderAmendPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amends        []*AmendItem           `protobuf:"bytes,1,rep,name=amends,proto3" json:"amends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAmendPayload) Reset() {
	*x = OrderAmendPayload{}
	mi := &file_tx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAmendPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAmendPayload) ProtoMessage() {}

func (x *OrderAmendPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAmendPayload.ProtoReflect.Descriptor instead.
func (*OrderAmendPayload) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{19}
}

func (x *OrderAmendPayload) GetAmends() []*AmendItem {
	if x != nil {
		return x.Amends
	}
	return nil
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x02tx\"]\n" +
	"\bSigEntry\x12\x1d\n" +
	"\n" +
	"signer_uid\x18\x01 \x01(\x04R\tsignerUid\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xe3\x01\n" +
	"\rMultiSigBlock\x12 \n" +
	"\x04sig1\x18\x01 \x01(\v2\f.tx.SigEntryR\x04sig1\x12 \n" +
	"\x04sig2\x18\x02 \x01(\v2\f.tx.SigEntryR\x04sig2\x12%\n" +
	"\x04sig3\x18\x03 \x01(\v2\f.tx.SigEntryH\x00R\x04sig3\x88\x01\x01\x12%\n" +
	"\x04sig4\x18\x04 \x01(\v2\f.tx.SigEntryH\x01R\x04sig4\x88\x01\x01\x12%\n" +
	"\x04sig5\x18\x05 \x01(\v2\f.tx.SigEntryH\x02R\x04sig5\x88\x01\x01B\a\n" +
	"\x05_sig3B\a\n" +
	"\x05_sig4B\a\n" +
	"\x05_sig5\"4\n" +
	"\x0fTransactionList\x12!\n" +
	"\x03txs\x18\x01 \x03(\v2\x0f.tx.TransactionR\x03txs\"\xd3\x03\n" +
	"\x11TransactionHeader\x12,\n" +
	"\n" +
	"chain_type\x18\x01 \x01(\x0e2\r.tx.ChainTypeR\tchainType\x12#\n" +
	"\rchain_version\x18\x02 \x01(\rR\fchainVersion\x12#\n" +
	"\aop_code\x18\x03 \x01(\x0e2\n" +
	".tx.OpCodeR\x06opCode\x12+\n" +
	"\tauth_type\x18\x04 \x01(\x0e2\x0e.tx.TxAuthTypeR\bauthType\x125\n" +
	"\x0eexecution_mode\x18\x05 \x01(\x0e2\x0e.tx.TxExecModeR\rexecutionMode\x12,\n" +
	"\vmarket_code\x18\x06 \x01(\x0e2\v.tx.MarketsR\n" +
	"marketCode\x12#\n" +
	"\rmarket_symbol\x18\a \x01(\rR\fmarketSymbol\x12\x1d\n" +
	"\n" +
	"signer_uid\x18\b \x01(\x04R\tsignerUid\x12\x14\n" +
	"\x05nonce\x18\t \x01(\x04R\x05nonce\x12\x1d\n" +
	"\n" +
	"min_height\x18\n" +
	" \x01(\x04R\tminHeight\x12\x1d\n" +
	"\n" +
	"max_height\x18\v \x01(\x04R\tmaxHeight\x12\x1c\n" +
	"\tsignature\x18\f \x01(\fR\tsignature\"\xa8\x01\n" +
	"\x18BatchedTransactionHeader\x12#\n" +
	"\aop_code\x18\x01 \x01(\x0e2\n" +
	".tx.OpCodeR\x06opCode\x12,\n" +
	"\vmarket_code\x18\x02 \x01(\x0e2\v.tx.MarketsR\n" +
	"marketCode\x12#\n" +
	"\rmarket_symbol\x18\x03 \x01(\rR\fmarketSymbol\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\"\xc8\x05\n" +
	"\vTransaction\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x15.tx.TransactionHeaderH\x00R\x06header\x12A\n" +
	"\fbatch_header\x18\x02 \x01(\v2\x1c.tx.BatchedTransactionHeaderH\x00R\vbatchHeader\x122\n" +
	"\tmeta_noop\x18\x03 \x01(\v2\x13.tx.MetaNoopPayloadH\x01R\bmetaNoop\x122\n" +
	"\tmeta_blob\x18\x04 \x01(\v2\x13.tx.MetaBlobPayloadH\x01R\bmetaBlob\x12;\n" +
	"\fmeta_reserve\x18\x05 \x01(\v2\x16.tx.MetaReservePayloadH\x01R\vmetaReserve\x12;\n" +
	"\forder_create\x18\x06 \x01(\v2\x16.tx.OrderCreatePayloadH\x01R\vorderCreate\x12;\n" +
	"\forder_cancel\x18\a \x01(\v2\x16.tx.OrderCancelPayloadH\x01R\vorderCancel\x12E\n" +
	"\x10order_cancel_all\x18\b \x01(\v2\x19.tx.OrderCancelAllPayloadH\x01R\x0eorderCancelAll\x12Q\n" +
	"\x14order_cancel_replace\x18\t \x01(\v2\x1d.tx.OrderCancelReplacePayloadH\x01R\x12orderCancelReplace\x128\n" +
	"\vorder_amend\x18\n" +
	" \x01(\v2\x15.tx.OrderAmendPayloadH\x01R\n" +
	"orderAmend\x128\n" +
	"\vsys_upgrade\x18e \x01(\v2\x15.tx.SysUpgradePayloadH\x01R\n" +
	"sysUpgradeB\r\n" +
	"\vheader_dataB\t\n" +
	"\apayload\"l\n" +
	"\x10BatchTransaction\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.tx.TransactionHeaderR\x06header\x12)\n" +
	"\apayload\x18\x02 \x03(\v2\x0f.tx.TransactionR\apayload\"+\n" +
	"\x0fMetaNoopPayload\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\".\n" +
	"\x12MetaReservePayload\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"]\n" +
	"\x11SysUpgradePayload\x12.\n" +
	"\tmulti_sig\x18\x01 \x01(\v2\x11.tx.MultiSigBlockR\bmultiSig\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x19\n" +
	"\aOrderID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xdf\x04\n" +
	"\tOrderItem\x12&\n" +
	"\border_id\x18\x01 \x01(\v2\v.tx.OrderIDR\aorderId\x12\x1c\n" +
	"\x04side\x18\x02 \x01(\x0e2\b.tx.SideR\x04side\x12,\n" +
	"\n" +
	"order_type\x18\x03 \x01(\x0e2\r.tx.OrderTypeR\torderType\x12,\n" +
	"\texec_type\x18\x04 \x01(\x0e2\x0f.tx.TimeInForceR\bexecType\x12\x1f\n" +
	"\vreduce_only\x18\x05 \x01(\bR\n" +
	"reduceOnly\x12\x1b\n" +
	"\tpost_only\x18\x06 \x01(\bR\bpostOnly\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\b \x01(\x04R\x05price\x12=\n" +
	"\x0fstop_price_type\x18\t \x01(\x0e2\x10.tx.TriggerPriceH\x00R\rstopPriceType\x88\x01\x01\x12\"\n" +
	"\n" +
	"stop_price\x18\n" +
	" \x01(\x04H\x01R\tstopPrice\x88\x01\x01\x12=\n" +
	"\x0ftake_price_type\x18\v \x01(\x0e2\x10.tx.TriggerPriceH\x02R\rtakePriceType\x88\x01\x01\x12\"\n" +
	"\n" +
	"take_price\x18\f \x01(\x04H\x03R\ttakePrice\x88\x01\x01\x12$\n" +
	"\vmarket_code\x18\r \x01(\rH\x04R\n" +
	"marketCode\x88\x01\x01B\x12\n" +
	"\x10_stop_price_typeB\r\n" +
	"\v_stop_priceB\x12\n" +
	"\x10_take_price_typeB\r\n" +
	"\v_take_priceB\x0e\n" +
	"\f_market_code\"\x92\x03\n" +
	"\tAmendItem\x12&\n" +
	"\border_id\x18\x01 \x01(\v2\v.tx.OrderIDR\aorderId\x12\x1f\n" +
	"\bquantity\x18\x02 \x01(\x04H\x00R\bquantity\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x04H\x01R\x05price\x88\x01\x01\x12=\n" +
	"\x0fstop_price_type\x18\x04 \x01(\x0e2\x10.tx.TriggerPriceH\x02R\rstopPriceType\x88\x01\x01\x12\"\n" +
	"\n" +
	"stop_price\x18\x05 \x01(\x04H\x03R\tstopPrice\x88\x01\x01\x12=\n" +
	"\x0ftake_price_type\x18\x06 \x01(\x0e2\x10.tx.TriggerPriceH\x04R\rtakePriceType\x88\x01\x01\x12\"\n" +
	"\n" +
	"take_price\x18\a \x01(\x04H\x05R\ttakePrice\x88\x01\x01B\v\n" +
	"\t_quantityB\b\n" +
	"\x06_priceB\x12\n" +
	"\x10_stop_price_typeB\r\n" +
	"\v_stop_priceB\x12\n" +
	"\x10_take_price_typeB\r\n" +
	"\v_take_price\"+\n" +
	"\x0fMetaBlobPayload\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\",\n" +
	"\x10MetaBatchPayload\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\";\n" +
	"\x12OrderCreatePayload\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.tx.OrderItemR\x06orders\"<\n" +
	"\x12OrderCancelPayload\x12&\n" +
	"\border_id\x18\x01 \x03(\v2\v.tx.OrderIDR\aorderId\"1\n" +
	"\x15OrderCancelAllPayload\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x93\x01\n" +
	"\x19OrderCancelReplacePayload\x127\n" +
	"\x11canceled_order_id\x18\x01 \x01(\v2\v.tx.OrderIDR\x0fcanceledOrderId\x12=\n" +
	"\x0ereplaced_order\x18\x02 \x01(\v2\x16.tx.OrderCreatePayloadR\rreplacedOrder\":\n" +
	"\x11OrderAmendPayload\x12%\n" +
	"\x06amends\x18\x01 \x03(\v2\r.tx.AmendItemR\x06amends*\x94\x01\n" +
	"\tChainType\x12\n" +
	"\n" +
	"\x06DEVNET\x10\x00\x12\v\n" +
	"\aTESTNET\x10\x01\x12\x12\n" +
	"\x0ePUBLIC_TESTNET\x10\x02\x12\x0e\n" +
	"\n" +
	"MAINNET_V1\x10\x03\x12\x0e\n" +
	"\n" +
	"MAINNET_V2\x10\x04\x12\x0e\n" +
	"\n" +
	"MAINNET_V3\x10\x05\x12\v\n" +
	"\aDARKNET\x10\x06\x12\x0f\n" +
	"\vCI_AUTOTEST\x10\a\x12\f\n" +
	"\bLOCALNET\x10\b*u\n" +
	"\n" +
	"TxAuthType\x12\a\n" +
	"\x03UID\x10\x00\x12\v\n" +
	"\aBATCHED\x10\x01\x12\x0e\n" +
	"\n" +
	"ED25519_PK\x10\x02\x12\x10\n" +
	"\fED25519_MSIG\x10\x03\x12\x0f\n" +
	"\vSEC256k1_PK\x10\x04\x12\x11\n" +
	"\rSEC256k1_MSIG\x10\x05\x12\v\n" +
	"\aUNKNOWN\x10\x06*V\n" +
	"\n" +
	"TxExecMode\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\b\n" +
	"\x04ASAP\x10\x01\x12\x0e\n" +
	"\n" +
	"IMMEDIATLY\x10\x02\x12\x11\n" +
	"\rCURRENT_BLOCK\x10\x03\x12\x0e\n" +
	"\n" +
	"NEXT_BLOCK\x10\x04*\xc7\x01\n" +
	"\aMarkets\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\r\n" +
	"\tPERPETUAL\x10\x01\x12\b\n" +
	"\x04SPOT\x10\x02\x12\f\n" +
	"\bAMM_SWAP\x10\x03\x12\x10\n" +
	"\fINVERSE_PERP\x10\x04\x12\x13\n" +
	"\x0fVANILLA_OPTIONS\x10\x05\x12\x15\n" +
	"\x11PERPETUAL_OPTIONS\x10\x06\x12\x13\n" +
	"\x0fDIGITAL_OPTIONS\x10\a\x12\x0e\n" +
	"\n" +
	"PREDICTION\x10\b\x12\n" +
	"\n" +
	"\x06TRADFI\x10\t\x12\v\n" +
	"\aINDICES\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06EXOTIC\x10\v*\xe6\x0f\n" +
	"\x06OpCode\x12\r\n" +
	"\tMETA_NOOP\x10\x00\x12\r\n" +
	"\tMETA_BLOB\x10\x01\x12\x10\n" +
	"\fMETA_RESERVE\x10\x02\x12\x0e\n" +
	"\n" +
	"META_BATCH\x10\x03\x12\x0f\n" +
	"\vSYS_UPGRADE\x10\x04\x12\r\n" +
	"\tSYS_PAUSE\x10\x05\x12\x0e\n" +
	"\n" +
	"SYS_RESUME\x10\x06\x12\x10\n" +
	"\fSYS_SET_FLAG\x10\a\x12\x17\n" +
	"\x13SYS_HEARTBEAT_CHECK\x10\b\x12\x1f\n" +
	"\x1bSYS_UPDATE_VALIDATOR_PARAMS\x10\t\x12\x15\n" +
	"\x11SYS_DEPOSIT_PAUSE\x10\n" +
	"\x12\x16\n" +
	"\x12SYS_WITHDRAW_PAUSE\x10\v\x12\x16\n" +
	"\x12SYS_DEPOSIT_RESUME\x10\f\x12\x17\n" +
	"\x13SYS_WITHDRAW_RESUME\x10\r\x12\x13\n" +
	"\x0fINS_FUND_CREATE\x10\x0e\x12\x0f\n" +
	"\vINS_FUND_OP\x10\x0f\x12\x0e\n" +
	"\n" +
	"INS_CREDIT\x10\x10\x12\r\n" +
	"\tINS_REPAY\x10\x11\x12\x0e\n" +
	"\n" +
	"INS_PAYOUT\x10\x12\x12\x16\n" +
	"\x12INS_AUTO_REBALANCE\x10\x13\x12\x14\n" +
	"\x10GOV_ASSET_CREATE\x10\x14\x12\x14\n" +
	"\x10GOV_ASSET_UPDATE\x10\x15\x12\x15\n" +
	"\x11GOV_MARKET_CREATE\x10\x16\x12\x15\n" +
	"\x11GOV_MARKET_UPDATE\x10\x17\x12\x15\n" +
	"\x11GOV_MARKET_FREEZE\x10\x18\x12\x17\n" +
	"\x13GOV_MARKET_UNFREEZE\x10\x19\x12\x15\n" +
	"\x11GOV_MARKET_SETTLE\x10\x1a\x12\x15\n" +
	"\x11GOV_MARKET_DELIST\x10\x1b\x12\x18\n" +
	"\x14GOV_SET_ACC_FEE_TIER\x10\x1c\x12\x13\n" +
	"\x0fGOV_FEE_COLLECT\x10\x1d\x12\x18\n" +
	"\x14GOV_INDX_ORACLE_FEED\x10\x1e\x12\x12\n" +
	"\x0eGOV_INDX_VALUE\x10\x1f\x12\x16\n" +
	"\x12GOV_MARKET_FUNDING\x10 \x12\x18\n" +
	"\x14GOV_BALANCE_TRANSFER\x10!\x12\x1b\n" +
	"\x17GOV_FEE_SCHEDULE_UPDATE\x10\"\x12\x0f\n" +
	"\vGOV_MESSAGE\x10#\x12\x17\n" +
	"\x13GOV_APPROVE_PROPOSE\x10$\x12\x14\n" +
	"\x10GOV_VAULT_CREATE\x10%\x12\x1c\n" +
	"\x18GOV_VAULT_PAUSE_DEPOSITS\x10&\x12\x1d\n" +
	"\x19GOV_VAULT_RESUME_DEPOSITS\x10'\x12'\n" +
	"#GOV_VAULT_EMERGENCY_ENABLE_WITHDRAW\x10(\x12\x10\n" +
	"\fACC_REGISTER\x10)\x12\x0f\n" +
	"\vACC_DEPOSIT\x10*\x12\x18\n" +
	"\x14ACC_WITHDRAW_REQUEST\x10+\x12\x16\n" +
	"\x12ACC_WITHDRAW_CLAIM\x10,\x12\x17\n" +
	"\x13ACC_WALLET_TRANSFER\x10-\x12\x10\n" +
	"\fACC_SET_FLAG\x10.\x12\x0f\n" +
	"\vACC_FEE_PAY\x10/\x12\x16\n" +
	"\x12ACC_AGENT_REGISTER\x100\x12\x14\n" +
	"\x10ACC_AGENT_REVOKE\x101\x12\x1b\n" +
	"\x17ACC_AGENT_UPDATE_LIMITS\x102\x12\x19\n" +
	"\x15ACC_SUBACCOUNT_CREATE\x103\x12\x19\n" +
	"\x15ACC_SESSION_HEARTBEAT\x104\x12\x14\n" +
	"\x10ACC_NONCE_UPDATE\x105\x12\x15\n" +
	"\x11ACC_WHITELIST_ADD\x106\x12\x18\n" +
	"\x14ACC_WHITELIST_REMOVE\x107\x12\x18\n" +
	"\x14ACC_KYC_SUBMIT_PROOF\x108\x12\x0f\n" +
	"\vACC_MESSAGE\x109\x12\x1a\n" +
	"\x16ACC_UPDATE_MESSAGE_KEY\x10:\x12\f\n" +
	"\bACC_VOTE\x10;\x12\x16\n" +
	"\x12ACC_CREATE_PROPOSE\x10<\x12\x0e\n" +
	"\n" +
	"ORD_CREATE\x10=\x12\x0e\n" +
	"\n" +
	"ORD_CANCEL\x10>\x12\x12\n" +
	"\x0eORD_CANCEL_ALL\x10?\x12\x16\n" +
	"\x12ORD_CANCEL_REPLACE\x10@\x12\r\n" +
	"\tORD_AMEND\x10A\x12\x0f\n" +
	"\vORD_REORDER\x10E\x12\x12\n" +
	"\x0ePOS_MARGIN_ADJ\x10F\x12\r\n" +
	"\tPOS_CLOSE\x10G\x12\x10\n" +
	"\fPOS_LEVERAGE\x10H\x12\v\n" +
	"\aPOS_ADL\x10I\x12\x0e\n" +
	"\n" +
	"POS_SETTLE\x10J\x12\x12\n" +
	"\x0eERC20_TRANSFER\x10K\x12\x0e\n" +
	"\n" +
	"ERC20_MINT\x10L\x12\x0e\n" +
	"\n" +
	"ERC20_BURN\x10M\x12\x11\n" +
	"\rERC20_APPROVE\x10N\x12\x10\n" +
	"\fERC20_FREEZE\x10O\x12\x12\n" +
	"\x0eERC20_UNFREEZE\x10P\x12\x11\n" +
	"\rVAULT_DEPOSIT\x10Q\x12\x1a\n" +
	"\x16VAULT_WITHDRAW_REQUEST\x10R\x12\x18\n" +
	"\x14VAULT_WITHDRAW_CLAIM\x10S\x12\x17\n" +
	"\x13VAULT_REWARDS_CLAIM\x10T\x12\x17\n" +
	"\x13VAULT_TOPUP_REWARDS\x10U\x12\x1c\n" +
	"\x18VAULT_EMERGENCY_WITHDRAW\x10V\x12\x1b\n" +
	"\x17KYC_COMPLIANCE_FLAG_SET\x10W\x12\x1d\n" +
	"\x19KYC_COMPLIANCE_KYC_UPDATE\x10X\x12\x19\n" +
	"\x15KYC_COMPLIANCE_FREEZE\x10Y\x12\x1b\n" +
	"\x17KYC_COMPLIANCE_UNFREEZE\x10Z\x12\x1d\n" +
	"\x19KYC_SANCTIONS_LIST_UPDATE\x10[\x12\x1a\n" +
	"\x15UNKNOWN_OR_UNREALISED\x10\xff\x0f\"\x04\bB\x10B\"\x04\bC\x10C\"\x04\bD\x10D*\x19\n" +
	"\x04Side\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x01*d\n" +
	"\tOrderType\x12\n" +
	"\n" +
	"\x06MARKET\x10\x00\x12\t\n" +
	"\x05LIMIT\x10\x01\x12\x0f\n" +
	"\vSTOP_MARKET\x10\x02\x12\x0e\n" +
	"\n" +
	"STOP_LIMIT\x10\x03\x12\x0f\n" +
	"\vTAKE_MARKET\x10\x04\x12\x0e\n" +
	"\n" +
	"TAKE_LIMIT\x10\x05*(\n" +
	"\vTimeInForce\x12\a\n" +
	"\x03GTC\x10\x00\x12\a\n" +
	"\x03IOC\x10\x01\x12\a\n" +
	"\x03FOK\x10\x02*Q\n" +
	"\fTriggerPrice\x12\r\n" +
	"\tMARKPRICE\x10\x00\x12\r\n" +
	"\tSPOTPRICE\x10\x01\x12\x12\n" +
	"\x0eLASTTRADEPRICE\x10\x02\x12\x0f\n" +
	"\vFUNDINGRATE\x10\x03B\x05Z\x03/txb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_tx_proto_goTypes = []any{
	(ChainType)(0),                    // 0: tx.ChainType
	(TxAuthType)(0),                   // 1: tx.TxAuthType
	(TxExecMode)(0),                   // 2: tx.TxExecMode
	(Markets)(0),                      // 3: tx.Markets
	(OpCode)(0),                       // 4: tx.OpCode
	(Side)(0),                         // 5: tx.Side
	(OrderType)(0),                    // 6: tx.OrderType
	(TimeInForce)(0),                  // 7: tx.TimeInForce
	(TriggerPrice)(0),                 // 8: tx.TriggerPrice
	(*SigEntry)(nil),                  // 9: tx.SigEntry
	(*MultiSigBlock)(nil),             // 10: tx.MultiSigBlock
	(*TransactionList)(nil),           // 11: tx.TransactionList
	(*TransactionHeader)(nil),         // 12: tx.TransactionHeader
	(*BatchedTransactionHeader)(nil),  // 13: tx.BatchedTransactionHeader
	(*Transaction)(nil),               // 14: tx.Transaction
	(*BatchTransaction)(nil),          // 15: tx.BatchTransaction
	(*MetaNoopPayload)(nil),           // 16: tx.MetaNoopPayload
	(*MetaReservePayload)(nil),        // 17: tx.MetaReservePayload
	(*SysUpgradePayload)(nil),         // 18: tx.SysUpgradePayload
	(*OrderID)(nil),                   // 19: tx.OrderID
	(*OrderItem)(nil),                 // 20: tx.OrderItem
	(*AmendItem)(nil),                 // 21: tx.AmendItem
	(*MetaBlobPayload)(nil),           // 22: tx.MetaBlobPayload
	(*MetaBatchPayload)(nil),          // 23: tx.MetaBatchPayload
	(*OrderCreatePayload)(nil),        // 24: tx.OrderCreatePayload
	(*OrderCancelPayload)(nil),        // 25: tx.OrderCancelPayload
	(*OrderCancelAllPayload)(nil),     // 26: tx.OrderCancelAllPayload
	(*OrderCancelReplacePayload)(nil), // 27: tx.OrderCancelReplacePayload
	(*OrderAmendPayload)(nil),         // 28: tx.OrderAmendPayload
}
var file_tx_proto_depIdxs = []int32{
	9,  // 0: tx.MultiSigBlock.sig1:type_name -> tx.SigEntry
	9,  // 1: tx.MultiSigBlock.sig2:type_name -> tx.SigEntry
	9,  // 2: tx.MultiSigBlock.sig3:type_name -> tx.SigEntry
	9,  // 3: tx.MultiSigBlock.sig4:type_name -> tx.SigEntry
	9,  // 4: tx.MultiSigBlock.sig5:type_name -> tx.SigEntry
	14, // 5: tx.TransactionList.txs:type_name -> tx.Transaction
	0,  // 6: tx.TransactionHeader.chain_type:type_name -> tx.ChainType
	4,  // 7: tx.TransactionHeader.op_code:type_name -> tx.OpCode
	1,  // 8: tx.TransactionHeader.auth_type:type_name -> tx.TxAuthType
	2,  // 9: tx.TransactionHeader.execution_mode:type_name -> tx.TxExecMode
	3,  // 10: tx.TransactionHeader.market_code:type_name -> tx.Markets
	4,  // 11: tx.BatchedTransactionHeader.op_code:type_name -> tx.OpCode
	3,  // 12: tx.BatchedTransactionHeader.market_code:type_name -> tx.Markets
	12, // 13: tx.Transaction.header:type_name -> tx.TransactionHeader
	13, // 14: tx.Transaction.batch_header:type_name -> tx.BatchedTransactionHeader
	16, // 15: tx.Transaction.meta_noop:type_name -> tx.MetaNoopPayload
	22, // 16: tx.Transaction.meta_blob:type_name -> tx.MetaBlobPayload
	17, // 17: tx.Transaction.meta_reserve:type_name -> tx.MetaReservePayload
	24, // 18: tx.Transaction.order_create:type_name -> tx.OrderCreatePayload
	25, // 19: tx.Transaction.order_cancel:type_name -> tx.OrderCancelPayload
	26, // 20: tx.Transaction.order_cancel_all:type_name -> tx.OrderCancelAllPayload
	27, // 21: tx.Transaction.order_cancel_replace:type_name -> tx.OrderCancelReplacePayload
	28, // 22: tx.Transaction.order_amend:type_name -> tx.OrderAmendPayload
	18, // 23: tx.Transaction.sys_upgrade:type_name -> tx.SysUpgradePayload
	12, // 24: tx.BatchTransaction.header:type_name -> tx.TransactionHeader
	14, // 25: tx.BatchTransaction.payload:type_name -> tx.Transaction
	10, // 26: tx.SysUpgradePayload.multi_sig:type_name -> tx.MultiSigBlock
	19, // 27: tx.OrderItem.order_id:type_name -> tx.OrderID
	5,  // 28: tx.OrderItem.side:type_name -> tx.Side
	6,  // 29: tx.OrderItem.order_type:type_name -> tx.OrderType
	7,  // 30: tx.OrderItem.exec_type:type_name -> tx.TimeInForce
	8,  // 31: tx.OrderItem.stop_price_type:type_name -> tx.TriggerPrice
	8,  // 32: tx.OrderItem.take_price_type:type_name -> tx.TriggerPrice
	19, // 33: tx.AmendItem.order_id:type_name -> tx.OrderID
	8,  // 34: tx.AmendItem.stop_price_type:type_name -> tx.TriggerPrice
	8,  // 35: tx.AmendItem.take_price_type:type_name -> tx.TriggerPrice
	20, // 36: tx.OrderCreatePayload.orders:type_name -> tx.OrderItem
	19, // 37: tx.OrderCancelPayload.order_id:type_name -> tx.OrderID
	19, // 38: tx.OrderCancelReplacePayload.canceled_order_id:type_name -> tx.OrderID
	24, // 39: tx.OrderCancelReplacePayload.replaced_order:type_name -> tx.OrderCreatePayload
	21, // 40: tx.OrderAmendPayload.amends:type_name -> tx.AmendItem
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	file_tx_proto_msgTypes[1].OneofWrappers = []any{}
	file_tx_proto_msgTypes[5].OneofWrappers = []any{
		(*Transaction_Header)(nil),
		(*Transaction_BatchHeader)(nil),
		(*Transaction_MetaNoop)(nil),
		(*Transaction_MetaBlob)(nil),
		(*Transaction_MetaReserve)(nil),
		(*Transaction_OrderCreate)(nil),
		(*Transaction_OrderCancel)(nil),
		(*Transaction_OrderCancelAll)(nil),
		(*Transaction_OrderCancelReplace)(nil),
		(*Transaction_OrderAmend)(nil),
		(*Transaction_SysUpgrade)(nil),
	}
	file_tx_proto_msgTypes[11].OneofWrappers = []any{}
	file_tx_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		EnumInfos:         file_tx_proto_enumTypes,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
